### ISSUE TITLE
[Feature request] Push notifications by using "SMS URL Callback"

### ISSUE THREAD

**Issue by fcastilloec** [michaelkourlas/voipms-sms-client#10]
I think there's a way to implement PUSH notifications instead of polling every couple of minutes for messages.
Voip.ms offers the option to forward your receive message to a URL address. If there's a central server that can receive those forwarded messages and then send them to my phone by using Android GCM, then the whole process will produce a true SMS replacement app.
I know that the biggest problem is creating the server, and maintaining it, but I'll be willing to pay for that service gladly!
If the problem is not creating the server but rather maintaining it, then the server code could be publish so each of as can ran our own home server that will take care of this.

**Comment by michaelkourlas** [comment]
I've looked into that feature myself and I think it'll work, though it'll obviously require additional setup work on the part of the end user. I'll see what I can do.

**Comment by bravo90078** [comment]
Thanks Michael for all the great work on the app. Obviously unless voip.ms changes their API it'll be harder to implement proper push notifications without having the user to run their own server;so maybe a compromise might simply be a polling interval "boost". On sending of a message, temporarily decrease the polling time down to 10 seconds before gradually increasing it back to the configured default of 15 mins.

**Comment by dkisselev** [comment]
Definite +1 on both ideas (GMS and variable polling times)

**Comment by michaelkourlas** [comment]
Good news - I've gotten push notifications working. I should be able to release a build soon.

**Comment by dkisselev** [comment]
How did you end up implementing it? I would assume that you'd to run the GMS server, so that server will receive every message callback with full contents?

**Comment by michaelkourlas** [comment]
Yes, I wrote a GMS server. The server doesn't send messages, though; it merely notifies the client that it should sync with the VoIP.ms servers to pick up the new SMS. The only parameter needed in the callback is the DID. The source code for the server is available [here](https://github.com/michaelkourlas/voipms-sms-server) if you're interested.

In theory I could allow users to host their own servers, but given how small the user base is I think I'll just host the server on [OpenShift](https://www.openshift.com/), who will do it for free.

**Comment by dkisselev** [comment]
It'd be nice if there was a way to get voip.ms to only send an identifier (like the DID) instead of the entire message body, but that's not really something you can fix.

Thanks for making it happen (y)

**Comment by michaelkourlas** [comment]
There is, actually. When you set the SMS callback URL in the DID settings, you choose which parameters are included in the URL. The server will never see the text of your messages if you don't want it to. In fact, it won't even work if you try to; it only accepts the DID as a parameter.

**Comment by dkisselev** [comment]
Huh, thanks! Their wiki doesn't reflect that, and I never actually tried turning it on. Awesome.

**Comment by michaelkourlas** [comment]
Push notifications have been added to the app as of the 0.3.0 release.
