### ISSUE TITLE
reliability issues with fdroid version

### ISSUE THREAD

**Issue by anarcat** [michaelkourlas/voipms-sms-client#102]
ever since i switched to using the version distributred through f-droid (cf. #36 and #54), i have been having weird reliability issues. for example, today i have received a "merry christmas" message from a friend: 4 days late. the message is dated "Sun 4:41 PM" but i actually received it just today, even though the phone was online intermittently since sunday.

sometimes i need to swipe down in the main screen to get new messages, even after waiting for the configured 1-minute synchronisation interval delay.

i have had a much more reliable experience when using GCM, even if i was doing that with the MicroG implementation...

would it be possible to ship a GCM-enabled version on f-droid, even if it's disabled by default? i understand that GCM implies using proprietary code on the server side, but it should be possible to make this work with free software on the client side, considering MicroG's work...

thanks!

**Comment by michaelkourlas** [comment]
I'm not surprised you're having reliability issues with the sync interval feature; later versions of Android muck around with alarms to preserve battery life (see [Doze and App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby.html)). Their solution is to -- you guessed it -- switch to FCM.

Is there actually a FOSS drop-in replacement for the FCM libs on the client side? Feel free to send me a link.

**Comment by anarcat** [comment]
i refered to microg project earlier:

https://microg.org/

this includes GmsCore, a GCM-compatible framework:

https://github.com/microg/android_packages_apps_GmsCore/wiki

i don't exactly know how it works - it may require signature spoofing
and such hacks.

ymmv.

**Comment by michaelkourlas** [comment]
Not sure a GCM lib will work now that VoIP.ms SMS has migrated to FCM.

Anyway, given the likely amount of work involved I don't think I'll be implementing something like this anytime soon. :(

I'm closing this, though #37 remains open.
