### ISSUE TITLE
Android Wear compatibility 

### ISSUE THREAD

**Issue by nathanbegin** [michaelkourlas/voipms-sms-client#103]
It might be nice to review the compatibility of the app with Android Wear.. because I am not able to answer my sms from my Android Wear smartwatch since I use voip.ms for talk and text with a data plan.

Nathan

**Comment by michaelkourlas** [comment]
Duplicate of https://github.com/michaelkourlas/voipms-sms-client/issues/34.

**Comment by nathanbegin** [comment]
Ok I see that its a duplicate ticket but the problem isn't fix yet  ???

**Comment by michaelkourlas** [comment]
No, I haven't added support for Android Wear yet.

**Comment by nathanbegin** [comment]
Oh I see, do you plan to add this feature soon?

**Comment by michaelkourlas** [comment]
It's not a top priority, unfortunately - maybe in release v0.4.8.

**Comment by nathanbegin** [comment]
It would be very nice for the Android Wear smartwatch users :)

By the way, the app is great ;)
