### ISSUE TITLE
15 digit contact "There are no messages in this conversation"

### ISSUE THREAD

**Issue by eshattow** [michaelkourlas/voipms-sms-client#104]
I received a message from a 15 digit contact, and the text of the message partially shows as it should in the overview. However, when I click into that received message I see no content only "There are no messages in this conversation." The content of the message is there from Settings|Edit Database. Why doesn't this show up in the context within the message thread?

App version is 0.4.6

**Comment by michaelkourlas** [comment]
Looks like a bug -- I'll take a look.

**Comment by michaelkourlas** [comment]
I can't reproduce this, unfortunately. Conversations with contacts with 15 digit numbers display fine on my device.
