### ISSUE TITLE
bug: Unread message shown in message list when click on them it says " there are no message in this conversation"

### ISSUE THREAD

**Issue by dnwk** [michaelkourlas/voipms-sms-client#117]
bug: Unread message shown in message list when click on them it says " there are no message in this conversation"
I have screenshots.

**Comment by michaelkourlas** [comment]
Not sure what's causing this, but hopefully it'll be fixed by my complete rewrite.

**Comment by michaelkourlas** [comment]
Hopefully fixed in 0.5.0.
