### ISSUE TITLE
Messages not displaying

### ISSUE THREAD

**Issue by pstenson** [michaelkourlas/voipms-sms-client#118]
Messages are not displaying in the main window ("You have no messages") and when I send a new message, it does get received, but still doesn't show up in the main window. Messages are there - if I go to Settings | Edit message database, I can see the text of the raw message format.
This is on a Blackberry Q10. All worked fine up until the most recent BB OS update.
Phil

**Comment by michaelkourlas** [comment]
Unfortunately this kind of problem is almost impossible for me to diagnose and fix because it's clearly device-specific and I don't own a BlackBerry Q10 :(

All I can say is that I'm in the middle of a major app rewrite; hopefully this bug will be fixed as a result of that.

**Comment by pstenson** [comment]
I would say the same thing! Unfortunate, because it was a very useful app up until that time.

I have tried erasing the database and re-downloading, also deleting the app and reinstalling - no joy. I wonder what would prevent it from reading the database correctly and displaying it. The rest of the display is fine - contact list looks like it always did, so perhaps it uses a different display method. If you have any suggestions, let me know and I'll try them.

Hopefully, the update will magically fix this.  Thanks for your comment.

Phil

**Comment by michaelkourlas** [comment]
Hopefully fixed in 0.5.0, which will be released soon.
