### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by sadortun** [michaelkourlas/voipms-sms-client#120]
Hi @michaelkourlas,

Thanks for this great app ! Do you think adding support for Android Auto is faisable ? It would be awesome !

Thanks,
Samuel

**Comment by dkisselev** [comment]
It's definitely possible, here's the documentation for how apps can register as Auto messaging providers: https://developer.android.com/training/auto/messaging/index.html

**Comment by sadortun** [comment]
Awesome ! I hope to see this in an upcoming release ! 👍

**Comment by michaelkourlas** [comment]
I've added Android auto support; it will be in the next release.
