### ISSUE TITLE
Conversation List Item phone number

### ISSUE THREAD

**Issue by adamzk** [michaelkourlas/voipms-sms-client#122]
Its always set to the user's number. Shouldn't it be the number of the relevant contact? Or perhaps to the number of the most recent message's author?

**Comment by michaelkourlas** [comment]
That's by design. It's meant to be used to indicate the DID associated with a conversation.

**Comment by michaelkourlas** [comment]
With that said, maybe the DID should be hidden if you only have one configured.

**Comment by Rolnaz** [comment]
Great idea Michael

**Comment by michaelkourlas** [comment]
Fixed in 0.5.3.

**Comment by adamzk** [comment]
That was fast. You're awesome.

On Jun 16, 2017 5:43 PM, "Michael Kourlas" <notifications@github.com> wrote:

Closed #122 <https://github.com/michaelkourlas/voipms-sms-client/issues/122>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/michaelkourlas/voipms-sms-client/issues/122#event-1127667991>,
or mute the thread
