### ISSUE TITLE
Not getting notifications sometimes

### ISSUE THREAD

**Issue by Rolnaz** [michaelkourlas/voipms-sms-client#123]
Hello Michael. First off thanks for this great app. And nice updates. 

One  issue I'm having now on nexus 6p stock is not getting all notifications. I've narrowed it down to two possibilities. They are either not coming through when my phones screen is off, or when i am only connected to wifi and H (when out of the city) and not 3g or lte. No other reports of this yet?

**Comment by michaelkourlas** [comment]
Try turning off battery optimizations -- your phone might be getting FCM pushes while not allowing the actual DB sync to complete.

**Comment by Rolnaz** [comment]
Optimizations are off, and there is no option to optimize this app either way.

**Comment by michaelkourlas** [comment]
To be clear, I'm talking about this:

![image](https://user-images.githubusercontent.com/1672388/27198363-d88f5c9e-51df-11e7-99f3-2aa113c1ec69.png)

**Comment by Rolnaz** [comment]
Got it. I didn't realize I had to change to show all apps. Found that it was optimized, changed it to not be. Will let you know if it still happens. Cheers

**Comment by michaelkourlas** [comment]
Closing for now, but comment if it's still an issue.
