### ISSUE TITLE
intermittently not able to sync

### ISSUE THREAD

**Issue by gmcaesar** [michaelkourlas/voipms-sms-client#124]
love the update but, now I get an error:

Synchronisation with Voip.ms failed, The voip.ms API response was not able to be parsed.

**Comment by michaelkourlas** [comment]
You're getting that error because the VoIP.ms response is malformed in some way. This probably isn't a problem with the app, but I'll try to improve the logging in 0.5.3 somewhat so that I can get a better idea of what's going on.
