### ISSUE TITLE
Unable to retreive old messages

### ISSUE THREAD

**Issue by lpbellerose** [michaelkourlas/voipms-sms-client#126]
I've just changed for a new phone and I tried to do the synchronization (put the retrieve date before I signed in, added the option to retrieve locally deleted messages and did a swipe down), but it doesn't seem to get anything. Did I do something wrong?

**Comment by michaelkourlas** [comment]
I think synchronization >3 months ago is broken at the moment -- I'm looking into it.

**Comment by pstenson** [comment]
From issue 125: I updated to latest 0.5.3. Retrieval message has change to "Synchronization failed: VOIP.ms API returned error 'invalid_daterange'". My synchronization start date is Dec 15 2015, but I tried several different dates in that month and all returned the same error.

**Comment by michaelkourlas** [comment]
A fix for this will be in the next release.
