### ISSUE TITLE
Shortcode and international message threads don't work correctly

### ISSUE THREAD

**Issue by eshattow** [michaelkourlas/voipms-sms-client#128]
Follow up to bug #104 I received a message from "011732873" that shows message body in the summary only. When I click through to message view it is blank "There are no messages in this conversation." The message cannot be marked as read, and cannot be deleted from VOIP.ms SMS client. Message can be viewed and deleted from https://voip.ms/m/sms.php however no reply can be sent from either that interface or the voipms-sms-client because international messages are not supported by Voip.MS service.

Problem is that the message cannot be interacted with from voipms-sms-client.

**Comment by michaelkourlas** [comment]
I really can't understand how this is possible, given that I can receive messages from non-standard numbers (e.g. shortcode numbers) without any difficulties.

Can you send me a copy of your database with that message (and preferably with all other messages deleted)?

**Comment by eshattow** [comment]
I have emailed privately the database edited as described.

**Comment by mobad** [comment]
I can also confirm a similar problem but I can't come up with a way to replicate it.
It might have something to do with receiving from a number that you can't send to or something...
The conversation for me says it has a draft but when I open it, it doesn't populate the text field with the draft and I can't delete it.

**Comment by dnwk** [comment]
I have experienced something similar. Especially when it is none English text.

**Comment by michaelkourlas** [comment]
Figured it out! Will be fixed in 0.6.0.

**Comment by jeff-dagenais** [comment]
Hi Michael,

I am wondering how/if you got this working. A voip.ms support person told me just now:

> Currently we can't send messages to short code numbers, or guarantee that text messages from short code numbers are received, only to/from local US, and Canadian 10 digit numbers. Short code numbers are usually used for automated services such as 2FA or verification.
> 
> Currently this is a limitation from our SMS provider end.

When I tried using the number for verification, I always have to use a voice message. SMS codes don't reach me... not even on my browser at sms.voip.ms.

Any clues? (Cannot user your nice app btw, apple. ;)

**Comment by dnwk** [comment]
This is a VOIP.ms problem. Some carrier could send to Bandwith.com number but not all the carriers.

**Comment by michaelkourlas** [comment]
I just fixed a bug that would prevent shortcodes from working in the app, but VoIP.ms still doesn't officially support them.
