### ISSUE TITLE
Add the number description. (Ex mobile, home, etc)

### ISSUE THREAD

**Issue by CharlesGEL** [michaelkourlas/voipms-sms-client#129]

**Comment by michaelkourlas** [comment]
To where?

**Comment by CharlesGEL** [comment]
When you click on a contact that has multiple numbers. There is no way to tell which one is what.

Same thing in a text thread. You see the contact name, the number but not the description.

It would be a nice add on.

**Comment by michaelkourlas** [comment]
There's not really any room for that, though -- where would you put it?
