### ISSUE TITLE
Notifications don't work all the time since last update

### ISSUE THREAD

**Issue by janvitos** [michaelkourlas/voipms-sms-client#130]
Hi,

Ever since the Voip.ms SMS application was recently updated, I'm not receiving message notifications all the time anymore.

It seems like it might have something to do with Nougat's doze mode because the notifications stop working when the phone has been asleep for a bit.

To get the messages, I need to go in the app and refresh the sms messages screen.

If you need more information or someone to test, I'll be glad to help.

This problem occurs on both my Google Pixel & Nexus 5X phones running Android Nougat 7.1.2.

Thank you.

**Comment by janvitos** [comment]
So I've disabled Battery Optimisations for the Voip.ms SMS app, I'll report back with my findings.

**Comment by michaelkourlas** [comment]
I honestly doubt this issue has anything to do with the last update in particular. I think this is just a general problem where database syncs are interrupted by Android because they take too long. There's not really a way to fix this, short of disabling battery optimizations.

I suppose I could include more information in notifications, but that would pose a clear privacy problem.

**Comment by janvitos** [comment]
Hi @michaelkourlas ,

Thanks for the info.

The reason why I mentioned last update is because I've never had this issue up until recently after updating the app.

The only time I had a similar issue before was a few months back when I opened ticket #85 , but you had later fixed the problem.

But I can confirm that once again, I'm not receiving most sms messages when the phone is in doze mode.

I did a few tests today with battery optimisations off, and received all sms notifications successfully, but I want to do more tests before confirming anything.

Thank you.

**Comment by michaelkourlas** [comment]
Thanks for reminding me of #85 -- it looks like I forgot to configure my new FCM cloud function to set messages to high priority. I've fixed this now and hopefully it'll fix your problem (perhaps even with battery optimizations enabled).

**Comment by janvitos** [comment]
Thank you.

I'll be testing with battery optimisation enabled tomorrow and will let you know of the outcome.
