### ISSUE TITLE
Multiple texts for one continuous message

### ISSUE THREAD

**Issue by cvcfox** [michaelkourlas/voipms-sms-client#132]
Hi,

Not sure if this has been brought up.  When receiving texts messages, they are broken into what looks like a max set of characters and split over different lines/messages.  Is this a restriction of the Voip.MS service, or something to do with the app?  

Example:
iPhone --> Android text (Ohhh okie 😔. I was hoping to come but I don't think I'll be able to without a car. I'd meet you at the bus stop like last time but I'm not dressed for it today. And it's freezing out)

Ohhh okie 😔. I was hoping to come but I don't think I'll be able t
2017-06-29 13:50:58
Received by 613xxxxxxx
 
delete
m not dressed for it today. And it's freezing out
2017-06-29 13:50:59
Received by  613xxxxxxx
 
delete
o without a car. I'd meet you at the bus stop like last time but I'
2017-06-29 13:50:59
Received by  613xxxxxxx

Thanks for the awesome app!

**Comment by michaelkourlas** [comment]
Limitation of VoIP.ms, unfortunately.
