### ISSUE TITLE
Send attachments?

### ISSUE THREAD

**Issue by Ezerbeth** [michaelkourlas/voipms-sms-client#133]
Hi,

Not sure if this is a limitation of voip.ms or the app itself, but since I can receive pictures and other attachments, why can't I send any?

Great work on the app!

**Comment by michaelkourlas** [comment]
VoIP.ms doesn't support MMS yet, so you shouldn't be able to send or receive pictures and other attachments.

**Comment by fredvb** [comment]
Would be neat to have a addon that permits a server owner to set a upload URL, which permits the application to upload an attachment, generate a link and appends the URL to the SMS that would be sent. This would be a neat hybrid approach.
The feature would require the owner of the DID to own a server that can run code (so as to not incur any cost to you guys), and also permitting the DID owner to feel a bit more safe about where the attachments are are sent.

**Comment by michaelkourlas** [comment]
Unfortunately, that sounds like a lot of work for a feature that few people will use because of the work involved in setting it up.
