### ISSUE TITLE
Notifications interupt

### ISSUE THREAD

**Issue by gmcaesar** [michaelkourlas/voipms-sms-client#134]
New message arrives notification appears and then disappears immediately, even tone is interrupted. 

Recent update to Android 7.0 on Asus zenfone 3 Mac.

**Comment by michaelkourlas** [comment]
I'm afraid I have no idea what could be causing that problem, and nobody else has reported it so I have nothing else to go on.


________________________________

**Comment by gmcaesar** [comment]
What can I do to help trouble shoot this issue, I have already checked the power saving options, and my notification disables ect

**Comment by michaelkourlas** [comment]
If you have some experience with Android development, you could install a debug load, try to reproduce the issue, and take a look at logcat to see if something funny is going on.

**Comment by gmcaesar** [comment]
i have not worked in android dev before, outside of loading custom roms, but i would be happy to do this if you can send me instructions

**Comment by michaelkourlas** [comment]
I'm afraid I don't really have the time to walk you through the process. Unfortunately, if I can't reproduce the issue, I can't fix it. :(
