### ISSUE TITLE
"Failed to retrieve DIDs. An unknown error occurred."

### ISSUE THREAD

**Issue by bradmont** [michaelkourlas/voipms-sms-client#136]
I'm having trouble getting set up; when I try to retrieve the DIDs from settings, I get a dialog saying, "Failed to retrieve DIDs. An unknown error occurred.". I've tried on a couple of phones; my best guess at the cause is the presence of a + in my email address.

**Comment by bradmont** [comment]
Aww shoot, it was a configuration error. Sorry!

**Comment by j-mikhail** [comment]
@bradmont Can you specify what the configuration error was? I am having the same problem.

**Comment by j-mikhail** [comment]
For anyone else wondering, this error will occur if the haven't specified your accessible IPs on the Voip.ms API configuration page.
