### ISSUE TITLE
Make the SMS retrieval service a foreground service

### ISSUE THREAD

**Issue by anthonydahanne** [michaelkourlas/voipms-sms-client#137]
when new SMS are received, I need to open the app so that it will pull them.
No new notifications are being in the android notification tray.

the only times I saw notifications arrive, is when I used the app recently (no stopped by the OS yet)

I'm using 0.5.3 from google play store, on Android 6.0.1

Do I need to tell Android to allow the app to check every "interval period" ?
thanks !

**Comment by michaelkourlas** [comment]
You might try disabling battery optimizations; it's possible Android is killing the app before it has a chance to show notifications.

**Comment by ailicic** [comment]
Disabling battery optimizations in Nougat does not solve the problem. I have the same problem with battery optimizations off: Messages do not come in unless I do a force refresh on the app. Do you have any suggestions on how to resolve this issue?

**Comment by michaelkourlas** [comment]
In the next release I will be making the SMS retrieval service a foreground service; this might fix the problem.

**Comment by anthonydahanne** [comment]
right, same thing for me on Nougat (7.0); I ended up setting up my VOIP.ms DID to forward the SMS to another notification mechanism.
but that sucks... reliable notifications would be a huge win.

**Comment by neogalael** [comment]
I have the same problem. Which notification mechanism are you using anthonydahanne?

**Comment by michaelkourlas** [comment]
Probably email.

**Comment by anthonydahanne** [comment]
nope : SMS actually - people send me SMSs to my voip.ms DID, and it's configured to send a rest request to a server sending a SMS to the SIM I'm using.
Anyway, with voip.ms you have plenty of options to forward your SMS

**Comment by neogalael** [comment]
michaelkourlas, do you have an idea when this bug will be fixed? (When the next version of the app will be ready?)

**Comment by michaelkourlas** [comment]
I've been quite busy. I have no ETA at the moment.

**Comment by michaelkourlas** [comment]
This has been implemented and will be in 0.6.0.

**Comment by anthonydahanne** [comment]
oh great ! when is it gonna be released ? thanks

**Comment by anthonydahanne** [comment]
cool that seems to work now ! Thanks a lot @michaelkourlas !

**Comment by ailicic** [comment]
Confirmed working. Thank you!
