### ISSUE TITLE
[Feature Request] UI Enhancements

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#14]
Thanks again Michael for the latest update with the GCM notifications. That was quite unexpected and much appreciated. I do have however have a few minor suggestions from a UX perspective which aren't critical in anyway but hopefully others may have noticed as well.

1) Message scrolling when opening chat.  When a chat is opened, rather than immediately showing me the last message it starts from the beginning and scrolls down to the most recent message.  Normally not a big deal, but if there are quite a few messages in the history it takes several seconds for the scrolling to finish.

2) Screen repaint when beginning to type. Normally when viewing a chat, messages are displayed in fullscreen portrait mode with the last message on the bottom.  However when I click on the text field to beginning typing a message, it would be nice to have the last message remain directly above the text field, but currently the screen does not adjust.  You have to wait for the keyboard to appear and then scroll again to see the last message.

3) Delay when sending messages. 
Now obviously the amount of time it takes to delivery a message is dependent on things beyond the apps control; I understand the app is merely waiting for an OK response from the API. 
However from a UX perspective, it might be better that once the send button is pressed, the message is moved to the history and the entry field released so the user can continue typing. 

Meanwhile the thread in the background does the normal delivery process and waits for an OK.  As a user I personally don't need absolute confirmation that the message is delivered, I just assumed it will be at some point and I'm okay with that. However if users are absolutely concerned, then perhaps a "D" delivered flag on each message can be implemented to address that.

**Comment by michaelkourlas** [comment]
Thanks for your suggestions! I'm happy to say that I've already fixed 1 and
2 in my test build. 3 will take a little more work, but it's next on my
list.

**Comment by michaelkourlas** [comment]
Fortunately, 3 looks like it will also be possible. You should also see it in the next release.
