### ISSUE TITLE
SMS Default

### ISSUE THREAD

**Issue by 2CanSan** [michaelkourlas/voipms-sms-client#140]
Hello
I switched to a straight data plan using voip.ms and this app and been a godsend.
Is it possible to give the option to make Voip.ms SMS the default messaging app.
I have not found a solution yet, not sure how to assign this to enhancement.
Thanks

**Comment by dkisselev** [comment]
See #49 

Apps aren't allowed to take over the default SMS handler unless they can actually send and receive SMS messages (over the cell network). We've looked into it in the past and Michael concluded that it would take too much work to implement full SMS capabilities into the existing app.
