### ISSUE TITLE
Single conversation backup

### ISSUE THREAD

**Issue by Ezerbeth** [michaelkourlas/voipms-sms-client#141]
Hi,

Is there a way to backup and/or export single conversation? I've tried a few apps from the app store but they all seem to only find the Android app SMS, and not the VOIP ones.

I've seen the raw DB export option, but it's not human readable. It's great for a backup, but is problematic to export a single conversation.

I needed to report a scammer and had to take screenshots, a bit annoying. Perhaps it could be added in a later release?

Thanks!

**Comment by michaelkourlas** [comment]
This has been implemented.
