### ISSUE TITLE
Only works when app is running

### ISSUE THREAD

**Issue by DigiDAD** [michaelkourlas/voipms-sms-client#145]
Doesn't run as a background service. App must be open in foreground or background to receive texts and notifications.

**Comment by ailicic** [comment]
I have a similar experience on three different devices used by 3 different people. Messages either don't come in until a manual refresh or come in hours late. The result is the for 4G or wifi. How can this be resolved?

**Comment by ailicic** [comment]
I, too, resolved the issue with MacroDroid by using the Start App (new instance) on a 1 minute timer only when screen is off but then the app is always in front when the screen is turned on (can't program "back button" when screen is off). Did you find a more elegant solution?

**Comment by DigiDAD** [comment]
Here is my macro:

Trigger
   Screen Off
   Screen On

If clause: App Inactive
   Launch VoIP.ms SMS / Force New
End If
Launch VoIP.ms SMS / Keep Existing
Launch Home Screen

Some of it seems redundant but it works. The last line brings up the Home Screen after launching the app so it is the active app when the screen comes on.

**Comment by michaelkourlas** [comment]
Closing in favour of #137
