### ISSUE TITLE
Sending Emails to International Numbers

### ISSUE THREAD

**Issue by antonyupward** [michaelkourlas/voipms-sms-client#146]
Hi this may be entirely user failure - but how do I send a text message to someone who is outside of country code 1 (North America)?

I have tried 

```
 011 <country code> <number>
+ <country code> <number> 
```

In both cases <number> does not include leading zeros.

In both cases, I get "Failed to send message VOIP.ms API returned error  "invalid dest"

**Comment by michaelkourlas** [comment]
Not possible, see https://wiki.voip.ms/article/SMS
