### ISSUE TITLE
[Feature Request] Add action buttons to notification

### ISSUE THREAD

**Issue by fcastilloec** [michaelkourlas/voipms-sms-client#15]
It will be very helpful if there are some action button under the notification.
I think that at least "Mark as Read" and "Delete" should be there. If possible also a "Reply" that could either open the specific conversation and puts the focus on the *message_edit_text* field and the keyboard opened. If possible, a better quick reply window, similar to QKSMS, 8sms or the cyanogenmod one, that doesn't require the full app to be open.

**Comment by michaelkourlas** [comment]
You can really only add a maximum of two buttons before some of the text is replaced by ellipses, so I'm going with "Reply" and "Mark Read". (Delete requires synchronization with the VoIP.ms server, and it'll likely be used less often than either of the other two.) I'll see if I can create a quick reply window.

**Comment by michaelkourlas** [comment]
This feature (including the quick reply window) has been implemented will be present in the next release.

**Comment by fcastilloec** [comment]
Great! Thanks!
