### ISSUE TITLE
Received message appears twice

### ISSUE THREAD

**Issue by eshattow** [michaelkourlas/voipms-sms-client#154]
Sending from Google Voice a text message longer than 160-characters to VoIP.ms DID the VoIP.ms SMS app displays the whole received concatenated message twice.

**Comment by eshattow** [comment]
I have an open support ticket into VoIP.ms:

> Thu, Jan 25 2018 5:49pm - John Loria
> Hello Eric,
> Affirmative. Currently it seems that the messages are being truncated at 184 characters, and the rest isn't delivered, instead of being split on multiple messages of 160 maximum characters. 
> We'll let you know as soon as we have any update.
> Regards
> John Loria
> VoIP.ms Customer Service

Although it looks like a VoIP.ms problem, the timestamps at http://sms.voip.ms show identical and the content is the same; could there be a workaround to check for this?

**Comment by michaelkourlas** [comment]
In theory, maybe -- however, I want the app to faithfully represent the messages received from VoIP.ms.

This is a VoIP.ms issue -- it's on them to fix it.
