### ISSUE TITLE
Short code message threads are broken

### ISSUE THREAD

**Issue by zootboy** [michaelkourlas/voipms-sms-client#155]
I was testing this app with my newly-ported number, and it seems that the handling of short code numbers is broken somehow. I received a verification code from Amazon, which was sent via the number "011262966". The message appears in the inbox (including the content snippet), however when I tap the message it says "There are no messages in this conversation." and the message remains unread in the inbox. Another service with a 5-digit short code shows the same behavior, but regular phone numbers behave correctly.

Thanks for this very useful app!

**Comment by michaelkourlas** [comment]
Duplicate of #128.
