### ISSUE TITLE
View and copy contact phone number in conversation

### ISSUE THREAD

**Issue by mica** [michaelkourlas/voipms-sms-client#157]
The ability to select words from within a text message, not just each message in its entirety, would be nice. Also, the ability to select and/or copy the phone number you're chatting with.

**Comment by michaelkourlas** [comment]
The ability to select individual words in a text message would make it difficult to select the message in its entirety, especially for small messages.

The ability to copy the phone number is possible -- I'll probably implement that at the same time as the block list and per-contact colours.

**Comment by mica** [comment]
I think it would be more useful to have access to the usual copy/share/web search options via whatever range of text we need - for example when trying to look up an address that's been sent within a larger message.

**Comment by michaelkourlas** [comment]
You can still do that by copying the text of the message to a text editing app and selecting specific text there, whereas there's no other way to view message metadata or delete a message without selecting the message itself.

Moreover, Android Messages has the same behaviour as this app, and one of the primary design goals of this app is to provide a similar look and feel to Android Messages.

**Comment by michaelkourlas** [comment]
The contact phone number can now be copied by long pressing on the toolbar title. The DID phone number can also be copied by pressing on the corresponding menu item.
