### ISSUE TITLE
Push to F-droid

### ISSUE THREAD

**Issue by anthonydahanne** [michaelkourlas/voipms-sms-client#161]
As of today, still no trace of 0.6.0.or 0.6.1 in fdroid repo : 

https://f-droid.org/packages/net.kourlas.voipms_sms/

Could you please add the latest version to f-droid ? thanks !

**Comment by michaelkourlas** [comment]
I don't have any control over that, I'm afraid.

**Comment by anthonydahanne** [comment]
ah, it's supposed to "happen" when you push new tags , right ?

**Comment by michaelkourlas** [comment]
I'm not sure if they have any sort of automatic tag detection, or whether a maintainer has to manually update their repo. In any event, you should contact them for assistance.

**Comment by ailicic** [comment]
I contacted them. Here is there response:

Wait for it to be merged:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3470/

**Comment by ailicic** [comment]
Voip SMS has now been updated to 0.61 on F-Droid!
