### ISSUE TITLE
Facebook Messenger-style message bubbles

### ISSUE THREAD

**Issue by michaelkourlas** [michaelkourlas/voipms-sms-client#163]

**Comment by michaelkourlas** [comment]
https://developer.android.com/guide/topics/ui/bubbles

**Comment by yulman19** [comment]
This is a standard feature in Android 11...could it be implemented?

**Comment by michaelkourlas** [comment]
It's on my to-do list, but it's not as simple as just flipping a switch -- there's some work involved.

**Comment by michaelkourlas** [comment]
This will be in the next release.
