### ISSUE TITLE
F-droid version synchronization frequency

### ISSUE THREAD

**Issue by jghq** [michaelkourlas/voipms-sms-client#169]
> Since you are using the F-droid version of the app, it is necessary to schedule automatic synchronization to retrieve new messages.

I'm wondering how frequent the synchronization is in this mode.
Should this not be up to the user? (enhancement)

**Comment by michaelkourlas** [comment]
It is already -- that's the "Synchronization interval" option.

**Comment by jghq** [comment]
Sorry, I'm not sure what you mean. This is the only thing that appears on this screen. I cropped it out because there's nothing there. Nothing about a synchronization interval.

![sync](https://user-images.githubusercontent.com/31827586/45269395-09047980-b47d-11e8-99f2-351dea4e8629.png)

**Comment by jghq** [comment]
Because you said it's a bug and that some options were supposed to be there, I reset the app and here they are. No idea what it was, but please don't spend time on this if it was just me.

**Comment by michaelkourlas** [comment]
Unfortunately I can't reproduce this.
