### ISSUE TITLE
Debug data usage

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#17]
Hey Michael, 

Is there a way for me to enable debug on the app to have it logged its requests? Not a big deal but I noticed today that the app used over 50 megs of data in the background for the day. Just curious why that is assuming gcm is working

**Comment by fcastilloec** [comment]
I'm just speculating but it might be because of the way messages are downloaded. If you have a lot of SMS, the app downloads all of them and just check one by one if you have it already or not, this happens everytime a new message arrives. The app doesn't download just the new one. It downloads all SMS in the time period you've put under settings.
I hope this is the reason, instead of bug.

**Comment by michaelkourlas** [comment]
@fcastilloec is almost certainly right.

**Comment by bravo90078** [comment]
I thought it might have something to do with that, but I actually do not have that many messages. I think the difference yesterday though was I left the process open instead of killing it which is what I normally do.

At this rate over the past seven days the app has actually used as much data as chrome and twitter. And at most my entire SMS history would contain maybe 100 msgs tops. 

In the meantime I guess I can lower my retrieve range, but something is telling me the app is still polling for messages when I don't have it and am not interacting with it

**Comment by michaelkourlas** [comment]
The polling feature has been completely removed from the app. It only updates on request or after receiving a GCM message.

**Comment by bravo90078** [comment]
Yeah so I did a quick test case yesterday. I set my sync time to 1 day only so it means no messages to download. I started one convo, a typical "where we meeting/dinner" thread of about 50 messages and the app according to google data usage used about 6 megs. 

Not a super huge deal, but definitely very high for messaging.  Several multiples high.

Does the VoIP.ms api support a new messages only call? Or is it a purely time interval call?

**Comment by michaelkourlas** [comment]
No, unfortunately. You can only specify a date range.

You might argue that the app only needs to fetch messages after the most recent message downloaded, but there's a problem with that: if you delete messages from the VoIP.ms server, that won't be reflected in the app.

**Comment by fcastilloec** [comment]
I think that it's better to have it sync only from the last time. We just have to think of this app as the main SMS hub, just like in traditional SMS. The servers of VoIP.ms are just a back up. 
So, with this app, almost nobody would manage their SMS from the website anymore (I certainly don't).

**Comment by michaelkourlas** [comment]
If the app took that approach, though, how would it handle multiple DIDs?

**Comment by fcastilloec** [comment]
I haven't think about that, since I only use a single DID.
A way to reduce the data usage is by not requesting a server update after sending a SMS. We have all the info necessary to just write to the database instead of requesting for all the messages in the time frame. The only downside is that there'll be a slight difference between the date fields in the message, but this shouldn't be any problem compare to the savings in transmitted data.
I submitted some commits to the pull request that will help with this.

**Comment by michaelkourlas** [comment]
We also won't know the ID. It would be safer to just limit the request to the last day.

**Comment by fcastilloec** [comment]
When sending the sms, the ID is known. It's part of the response from the VoIP.ms API. You get an Array with:
(
    [status] => success
    [sms] => 23434
)

So, I simply used that ID to save the SMS on the database.

**Comment by michaelkourlas** [comment]
That's a good point. My working copy is quite different from what's in the repository at the moment, so I don't know if I'll be able to merge in these changes directly, but I'll see if I can get some of these fixes into the next release.

**Comment by michaelkourlas** [comment]
In general, I think I'll adopt the following approach:
- By default, the app will only update the database with messages later than the most recent message currently in the database. In addition, deletions of messages will not be automatically propagated to the VoIP.ms servers.
- However, there will be a 'Synchronize with VoIP.ms' option that will propagate any deletions, then reconstruct the entire database from the VoIP.ms servers.

**Comment by fcastilloec** [comment]
I don't see why we can't have an option that will also delete the server copy. I can see two ways around this.
First it's like a computer, deleting a message locally, for all intents an purposes, it will just "move it to the trash", but there's a way to "empty" the trash. You can keep only the IDs of the delete messages, and if the option to "empty the trash" is run, then all those messages get deleted from the server too. This can also have an optional automatic setting, "emptying the trash" every day, week, etc.
The other one, is to offer an option under settings which will change the behavior of the delete button, either by only deleting locally or both local and server. Or even a combination of both options.
In my opinion, I rather have a setting so I can choose weather to delete it everywhere or just locally

**Comment by fcastilloec** [comment]
@bravo90078 could you please try this release: [v0.4.2](https://github.com/fcastilloec/voipms-sms-client/releases/tag/v0.4.2)
It should use a lot less data, hopefully a fraction of what it used to use. I used to get ~1.5Gb a month on this app. I think I've gotten it down to a couple hundred megabytes a month. I'd like to see what's your experience with it. Thanks

**Comment by michaelkourlas** [comment]
I've been on vacation over the past couple of weeks; I'll get back to developing shortly.

**Comment by bravo90078** [comment]
@fcastilloec I've tried your version for a couple of days and it's definitely a huge improvement in terms of data usage.  It's no longer several multiples data usage of other messaging apps. I still encountered some weird scenarios where I received no msgs and did no refreshes for a day, but the app still triggered usage of 200kb for instance, but definitely no big deal as a whole. 

At this point any complaints I would be largely cosmetic and UX related; from a data usage standpoint i think the adjustments made have put it in the realm of more than acceptable.

**Comment by fcastilloec** [comment]
@bravo90078 Thanks for letting me know! Hopefully this modification will get pushed to the Google Play version by @michaelkourlas 
Regarding the UX, feel free to open any other issue/feature-request with a description of what you need/want so we can track it.

**Comment by bravo90078** [comment]
I think the only real pressing one I would say from a usability issue is to change the pull to refresh behavior to only check for messages since last received; as opposed to poll for the date range history.

A full message sync with the server should probably only be done on first setup/connection, and if manually invoked from the settings menu. I'll make an item for this, but the rest of the UX issues I would say are more preference than actual hindrances.

**Comment by michaelkourlas** [comment]
Thanks for your update, @fcastilloec!

I'm presently working on a large update that involves a number of architectural changes, so that's why it's taking so long :(

Once it's finished I'll merge your changes in and start taking a look at the new issues from @bravo90078.

**Comment by michaelkourlas** [comment]
The changes I made should substantially reduce data usage. They're very similar to @fcastilloec 's changes. I'll close this issue for now, but let me know if there are any further issues.
