### ISSUE TITLE
Application crash when changing notification sound

### ISSUE THREAD

**Issue by neogalael** [michaelkourlas/voipms-sms-client#173]
I am on a Moto G5 and when I try to change the notification sound, the application crashes. I tried it many times and it crashes each time.

**Comment by michaelkourlas** [comment]
This is a recurring issue which I'm not quite sure how to fix, given that the app already asks for the required external storage permissions.

**Comment by michaelkourlas** [comment]
Unfortunately, I simply do not know how to reproduce this.
