### ISSUE TITLE
Push notifications not working and crash when trying to disable/enable notifications

### ISSUE THREAD

**Issue by electoys** [michaelkourlas/voipms-sms-client#176]
Push notifications stopped working awhile ago.  I checked my URL callback at voip.ms and it's set correctly.  I also tried disabling and re-enabling the notifications setting, but the app crash when I change that setting.  I've sent a crash report from the phone.  Is there anything else you need to understand the problem?

(I'm running versoin 0.6.1 on Android 6.0 on an HTC One m8.)

Thanks for the great app.  I'm a proud supporter.

**Comment by githubgabster** [comment]
Same for me, running on Android 5.1.

**Comment by cdrage** [comment]
@electoys I believe this has been resolved? I remember in December that the service was down briefly due to Google's servers having issues.

**Comment by michaelkourlas** [comment]
Push notifications are working for me, so closing.

**Comment by githubgabster** [comment]
It was an issue with Google servers, indeed.

Le lun. 25 mars 2019 09 h 04, Michael Kourlas <notifications@github.com> a
écrit :
