### ISSUE TITLE
Message sorting

### ISSUE THREAD

**Issue by pcpumpkin** [michaelkourlas/voipms-sms-client#177]
Any way to sort messages so that most recently received/sent appear at top?

**Comment by michaelkourlas** [comment]
No, and I'm not sure there's a good use case for such a feature. When you open the conversation view, you automatically scroll to the bottom.

**Comment by pcpumpkin** [comment]
Sorry, my misunderstanding. I had a bunch of drafts from different contacts
that were stuck to the top of the opening page.  I deleted them and now all
the most recent contact messages appear at the top.

PC
