### ISSUE TITLE
Copy message content

### ISSUE THREAD

**Issue by govis** [michaelkourlas/voipms-sms-client#185]
First off - great app, thanks a lot for maintaining it.
I noticed that in the last update copying a message stopped working. I could do it before when someone texts me an address I was able to copy the message by tapping and holding it and then paste it into another app such as google maps. Doesn't seem to work anymore after the last update to 0.6.4 on Android 9.

**Comment by michaelkourlas** [comment]
I can reproduce this issue, but only for messages with links. Is that what you're seeing?

**Comment by govis** [comment]
Right, didn't realize it was a link that was causing it. Thanks

**Comment by michaelkourlas** [comment]
This bug should be fixed in the 0.6.5 release.
