### ISSUE TITLE
Investigate maximum message length issues

### ISSUE THREAD

**Issue by michaelkourlas** [michaelkourlas/voipms-sms-client#186]
This is a VoIP.ms bug.

The VoIP.ms API is treating the characters ' and " (at least -- there might be others) as taking two characters instead of one.

I've opened a ticket with them. Others might want to do so as well.

**Comment by cdrage** [comment]
Hey @michaelkourlas I'm assuming this is related to the recent`sms_too_long` errors?

**Comment by julianlam** [comment]
Is it an issue with their (VoIP.ms's) end? Should we bug them incessantly for updates? :laughing:

**Comment by michaelkourlas** [comment]
This is a VoIP.ms bug.

The VoIP.ms API is treating the characters `'` and `"` (at least -- there might be others) as taking two characters instead of one.

To reproduce, send the following message via the API, and them via http://sms.voip.ms. It will fail in the former case and succeed in the latter case.

```This is a test SMS message that uses the ' character and which is exactly 160 characters long. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa```

**Comment by michaelkourlas** [comment]
I've opened a ticket with them. Others might want to do so as well.

**Comment by julianlam** [comment]
Will do, thanks for the explanation!

**Comment by michaelkourlas** [comment]
The latest from VoIP.ms:

>Hello Michael,
>
>This is still being looked into.
>
>We apologize for the delay.
>
>Regards.
>
>__
>John Loria
>VoIP.ms Customer Service

**Comment by noryb009** [comment]
Until the bug is fixed upstream, does it make sense for this app to also count `'` and `"` incorrectly?

**Comment by michaelkourlas** [comment]
I'm hoping they'll fix it first. I'd rather not implement the workaround and then have to remove it later.

**Comment by michaelkourlas** [comment]
Looks like they fixed this.

**Comment by Whateverman2012** [comment]
Just experienced it...
I use french. Maybe a 'special' characters issue.
