### ISSUE TITLE
Use both Android and VOIP.ms phonebooks.

### ISSUE THREAD

**Issue by kezimod** [michaelkourlas/voipms-sms-client#189]
If I want to have names for numbers appear I have to add people in my Android phone book too. To take advantage of VOIP.ms's ability to route and block calls I use their phonebook system, not Androids. It would be handy to use names from there.

**Comment by michaelkourlas** [comment]
This is not something I'm likely to implement, unfortunately.

**Comment by kezimod** [comment]
Just to make sure that I understand the situation correctly: At the moment voip-sms-client assigns names to threads based upon Android (not VOIP.ms's) phone book entry for the phone number. There is not a way to import the VOIP.ms phone book into the Android phonebook system or to have voip-sms-client use the VOIP.ms phonebook for it's names instead of the Android phonebook?

**Comment by michaelkourlas** [comment]
I'm sure there's a way to do both. This is a hobby project of mine, though -- I only work on features that I am interested in or that I think are in high demand, and this does not fall in either category.

I'd suggest manually importing your VoIP.ms phonebook into the Android phonebook.
