### ISSUE TITLE
Cannot send SMS (but Grandstream Wave can) 

### ISSUE THREAD

**Issue by edwardjohnson11** [michaelkourlas/voipms-sms-client#191]
I use the SMS app for SMS and grandstream Wave for calls. 

The SMS app was working as normal when suddenly messages failed to send.

However, using grandstream wave, I continued to be able to send messages, using the same credentials. After sending those messages on GSV, those messages appear in the SMS app, but I still can't send new messages through the SMS app.

**Comment by edwardjohnson11** [comment]
Mysteriously, the SMS sending is working again... On its own

**Comment by michaelkourlas** [comment]
Glad to hear it's working!

**Comment by michaelkourlas** [comment]
Glad to hear it's working!
