### ISSUE TITLE
SMS notifications don't appear (F-Droid only)

### ISSUE THREAD

**Issue by tgharib** [michaelkourlas/voipms-sms-client#196]
I'm using Android 9 (AOSPExtended) on the Redmi Note 4. I don't have google apps and I am using the f-droid version. All permissions are given (contacts, phone, storage) and battery optimizations are disabled. Notifications have never worked (sync interval is 30 minutes). I'm not sure how to debug/diagnose this issue. I'm currently working around it using macrodroid.

**Comment by mang1ed** [comment]
Hi, I'm running e.foundation (lineage fork) on my phone and am experiencing the exact same issue. I have also the fdroid version VoIP.ms and set the sync interval time to 1 minute. It will work for the first few messages until I refresh the list manually (minutes/hours later), then I will see the rest of them appear.

**Comment by tgharib** [comment]
Hi, I actually switched from Android to Ubuntu Touch and wrote my own simple Ubuntu Touch app that creates a notification when you receive a text message: https://open-store.io/app/voipmssmsnotifier.tgharib

If you don't want to change operating systems, I recommend to either work around it using macrodroid (to launch the app in regular intervals) or to try other voip.ms apps:

https://play.google.com/store/apps/details?id=com.pcability.voipconsole

https://play.google.com/store/apps/details?id=io.github.felixzheng98.voipmstools

**Comment by mang1ed** [comment]
Thank you for the alternatives. I ended up switching to sms via SIP network on Bria mobile app for the moment.  I am still waiting for my brave heart edition pinephone to arrive 😎

**Comment by michaelkourlas** [comment]
I'll look into this, but in general Google has made it progressively more difficult to use a timer-based method for receiving notifications.

Personally, I don't use this version of the app -- I use the one that supports push notifications.

**Comment by mang1ed** [comment]
Is the push version the one listed on the play store? Can this also be downloaded via your github repo?

**Comment by michaelkourlas** [comment]
Yes, primary is the push notifications one. It requires Google Play Services.

**Comment by JohnMertz** [comment]
I'm using the same basic setup as OP: Rom without GAPPs (Lineage, in my case), Android 9 equivalent, version from F-droid.

Out of the box, notifications don't work, however, when I go to Settings->Notifications, this is because it defaults not to show notifications.After enabling notifications from there, they work fine. 

Default synchronization interval is also set to "Never". These are 2 things worth checking for anyone experiencing the same issue.

**Comment by michaelkourlas** [comment]
Huh, that's odd. It should default to notifications enabled. I'll look into that as well.

**Comment by mang1ed** [comment]
On e.foundation they were enabled on default. However I had to optimise the battery to keep the app awake. I took your advice Michael and tried the push version and noticed that even with intervals set to never, it did not update on its own. I had to set a time to get it to sync as well. I may have to open another thread but also sending messages would give me an error. I believe it may have something to do with microg registration.

**Comment by michaelkourlas** [comment]
Sending messages has nothing to do with Google. What error are you getting when you try to send a message? "sms_failed"?

**Comment by mang1ed** [comment]
Yes exactly however, strangely, after reactivating my API again, its working. Not sure why it happened.

**Comment by sinisterintentions** [comment]
@mang1ed this seems to be an intermittent issue with the API over the last few days. I wrote a CLI client that is getting the same result occasionally. I've been able to get by with the SMS to email functionality; replies on that still work. I just opened a ticket with VoIP.ms. Probably not a problem with the app itself.

**Comment by michaelkourlas** [comment]
I just tested the F-Droid version of the app on my own device (a Pixel 2 XL running Android 10) and synchronization works correctly, even after a reboot without opening the app afterwards.

This is probably an OS or device-specific issue, which unfortunately will make it almost impossible for me to debug, assuming it's even a problem with the app.

**Comment by tgharib** [comment]
Not that it matters anymore since I've switched operating systems but it might've been because I had neither gapps nor microg.
