### ISSUE TITLE
[Question] What information is passed to the google cloud function

### ISSUE THREAD

**Issue by Sytten** [michaelkourlas/voipms-sms-client#197]
Hi!
Thanks for this amazing app. I was wondering was information is sent and/or collected by the GCP cloud function. Is the code open source? I am a bit worried about it and I would prefer to self host it if possible (a setting to change the base url which is currently hard coded would be perfect).
Thanks

**Comment by michaelkourlas** [comment]
Just your DID. Yes, it is [open source](https://github.com/michaelkourlas/voipms-sms-firebase). You can self-host it, but I'm afraid it's not as simple as changing a setting in the app. You have to sign up for a Firebase account and use your own google-services.json file when compiling the app.

**Comment by Sytten** [comment]
Hum thats annoying, but thanks for the quick reply. With further research I understand how the syntax works for the callback and the message is not sent to the function (which was what worried me).
