### ISSUE TITLE
Font kerning in list and message display is too open

### ISSUE THREAD

**Issue by athompso** [michaelkourlas/voipms-sms-client#199]
In both the conversation list screen and the message screen, the font kerning puts far too much space between each letter, resulting in a slightly odd look that's hard to read.
I'm guessing this might be because I've got the system scaling turned up a bit so I can, y'know, read the text on my screen, but am not sure.  If so, the toolkit or API calls are interpreting something wrong.
I do have the ability to sideload for testing.

**Comment by athompso** [comment]
I can also forward screencaps privately, I'd prefer not to share my messages with all of GitHub ;-)

**Comment by michaelkourlas** [comment]
You can email me screencaps if you want at michael@kourlas.com.

I use the [material design text styles](https://material.io/design/typography/the-type-system.html#) for the message and conversation views, and I have noticed that the font kerning is different from the Android defaults.

**Comment by athompso** [comment]
The body text in the Voip.ms SMS app appears to be using a "display" style with extra letter spacing.  That's one of the prime no-nos in text formatting.  I can't tell what style is in use, but it's not just kerning.
Screenshots sent directly to Michael.

**Comment by michaelkourlas** [comment]
Actually, the message text in the conversations and conversation view use `TextAppearance.MaterialComponents.Body2` and `TextAppearance.MaterialComponents.Body1` respectively, so blame Google :P

**Comment by athompso** [comment]
Oh, barf.  Well, I blame Google for many other things, that just adds one more to the list.  Anyway, I suggest at least letting users customize the fonts/styles in order to get us out of your hair.

**Comment by athompso** [comment]
Quoting from Google's article about their research that went into the text field design:

> Material Design’s goal was to determine how to improve the text field to make it more distinguishable, easier to read, and more understandable — with a more clear touch target. We wanted users to be able to fill out a form correctly and quickly.

...except these aren't text fields I'm complaining about.
(That's from https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03, BTW)

**Comment by michaelkourlas** [comment]
Sure, but [these styles](https://material.io/design/typography/the-type-system.html#) aren't meant to apply to text fields exclusively.

I think it's unlikely I will make the styling configurable, but I will look at making it more like Google Messages, since that's one of the design goals of this app.

**Comment by athompso** [comment]
I don't suppose you have a beta APK build with this change, that I can test?

**Comment by michaelkourlas** [comment]
No -- you'll have to do a manual build if you want to preview the changes.
