### ISSUE TITLE
Sluggish drawing performance when pulling up chats with long message history

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#20]
It was previously noted that when opening a chat with a long chat history the app would start from the beginning and scroll all the way to the end.  While visually the app no longer does this, it appears in the background it still does do this, as the time to pull up the chat is correlated with the length of the chat history. (i.e. More chat history means longer to pull up chat).

I would propose when pulling up chat history, really only the last 10 messages need to be pulled and drawn to the screen.  The remaining messages don't really need to be looked up and loaded until the user starts scrolling back; this should greatly improve the responsiveness of pulling up the app.

**Comment by michaelkourlas** [comment]
It's true that the current behaviour is to load the entire conversation is loaded into the conversation window. I'll see if I can load views on demand instead.

**Comment by ASalvail** [comment]
It might be linked, but performance has been a huge issue for me in using the app as a replacement for regular SMS. Each time I open the app to read a message, the app needs between 4 and 10 seconds to open. It might be because the DB is in JSON and it needs to iterate through the whole library each time?

**Comment by michaelkourlas** [comment]
No, the app uses an actual relational database. The JSON is just for import/export.

**Comment by ASalvail** [comment]
Any idea why it would take so long to open then?

**Comment by Playdifferent** [comment]
I have to delete all msgs regularly to keep this app from taking a long time to load

**Comment by michaelkourlas** [comment]
0.5.0 contains numerous performance improvements that should fix this problem.
