### ISSUE TITLE
Previous version compatibility

### ISSUE THREAD

**Issue by Bruneux** [michaelkourlas/voipms-sms-client#202]
Hi

I saw that the last version compatible with Kitkat (4.4) and under is the 0.5.3. I guess it hasn't been updated in the last three years for these versions of Android. Is there any security or stability risk in using this version? Or do I have another option for my Galaxy S3?

**Comment by michaelkourlas** [comment]
Honestly, I don't recall. I don't recommend using anything other than the latest version.
