### ISSUE TITLE
Rate limit of push notification makes the notification inconsistent

### ISSUE THREAD

**Issue by hdlineage** [michaelkourlas/voipms-sms-client#207]
I noticed my inconsistent push notification is due to rate limiting of the webhook server.
When using voip.ms or public services like ifttt to call the webhook, during peak hours I often fail to get push notification due to possibly many people calling the webhook from the same ip address.
I currently setup a self-hosted webhook service to call the update and it works great.
Could you elaborate on this issue? Maybe whitelisting certain public ips is a good idea for false positives?

**Comment by michaelkourlas** [comment]
Sorry, I set some quotas to avoid any sudden billing surprises and it seems they're too low. Hopefully this is now fixed, but please let me know if you continue to see issues.
