### ISSUE TITLE
Delay in sending messages

### ISSUE THREAD

**Issue by smnc** [michaelkourlas/voipms-sms-client#208]
My Acer Chromebook Tab10 sometimes has serious delays when sending messages.

I type out a message and hit send. The message dissapears from the text input box like a normal send but doens't show up in the conversation. It also doesn't show up in sms.voip.ms
At some point afterwards (seems to be a bit over 10 minues on average), the message actually sends and shows up as part of the conversation.

Syncing the app, closing and reoping the app, and even restarting the device seem to have no impact.

Making it weirder is that the time of the delay seems to vary wildly. I've had delays of only a few minutes, and delays of ~20 minutes. And sometimes it doesn't happen at all and works normally.

By suspicion is that it's something to do with the implementation of Android apps in ChromeOS, but I'm not a coder and this is just a guess. Unfortunately I don't have access to a different ChromeOS device to test my theory.

**Comment by michaelkourlas** [comment]
Unfortunately I think it's very unlikely that I'll be able to identify and fix this bug.

**Comment by smnc** [comment]
I expected as much. I'll update if if gain any new insights or information. 
Thanks!
