### ISSUE TITLE
Messages sent via notification widget are not shown in the chat history

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#21]
When performing a quick reply from the notification widget, the response is not present when you open the chat with that user.

It'll only appear once you to a forced full sync which then pulls it from the server.

**Comment by fcastilloec** [comment]
I'm trying to replicate this problem but I can't. The same function used to send messages from the app itself is also used to send the messages from the QuickReply, so there's no reason at all for them to not show up.
I've tried replying to some messages and they all show up in the conversation.

**Comment by michaelkourlas** [comment]
I can't replicate this problem either. Closing for now. @bravo90078, with that said if you could provide any more information it would be much appreciated.
