### ISSUE TITLE
Message order is backwards when receiving split messages

### ISSUE THREAD

**Issue by DroidCry** [michaelkourlas/voipms-sms-client#212]
Hi, 
I just edited my review on google play before realizing that you had this on GitHub. I don't want you to think I'm pestering for this bug but I figured it might be easier to have it here for you.
When I was looking at the message details I noticed that even messages received at the same timestamp do have a message ID that is consistently in ascending order. Perhaps this could be a potential solution for sorting messages that come in at the same time when they are split. Of course, I have no idea how you have done this and what is available in code. I just like this app SO much better than the alternatives and this is the only thing that makes it a little confusing to use.
Cheers for all the work that has gone into this!

**Comment by smnc** [comment]
I've experienced the same issue. 
Ideally it'd be nice if the app could stitch together a multi-part SMS - I definitely recall apps doing that in the (distant) past before the move to use MMS for longer messages, but just displaying them in the correct order would be a huge improvement.

**Comment by michaelkourlas** [comment]
Are you saying that the message IDs are in the correct order? In other words, if we sorted messages with the same timestamp by message ID, they would appear in the correct order?

**Comment by DroidCry** [comment]
I thought this was the case as the last several conversations I checked this was true. I've just spent some time going back over more of them and it seems like that was just coincidence. Sorry for the false lead.

**Comment by michaelkourlas** [comment]
I just did some testing and it looks like the message ID order is correct in at least some cases. This is a relatively straightforward fix, so I'll give it a shot.
