### ISSUE TITLE
Custom Font Size

### ISSUE THREAD

**Issue by g0pher666** [michaelkourlas/voipms-sms-client#213]
The Settings > Appearance page should allow the user to set a custom font size (small, medium, large, or point size).  Using the system font size helps, but setting this as a custom setting would make it more accessible for people with poor vision.

Also, similar to the Samsung Messages app, when a user has opened a conversation, pressing the hardware Volume + or Volume - should make the text font size get larger or smaller.

**Comment by michaelkourlas** [comment]
Unfortunately, this isn't as simple as I thought it might be. I think adjusting the system font size will have to do.
