### ISSUE TITLE
"No configured DIDs"

### ISSUE THREAD

**Issue by dm17** [michaelkourlas/voipms-sms-client#214]
I have enabled the API, set a password, logged into VoIP.ms SMS with it, and also enabled SMS on that DID. I'm using the latest F-Droid version. Any ideas why this would not work? In settings -> phone numbers -> it says to use the voip.ms phone number configuration menu, which I did.

**Comment by moreause** [comment]
don't forget to fill the url call back

if you don't you just see the message when you open the app or do a refresh

**Comment by dm17** [comment]
> don't forget to fill the url call back
> 
> if you don't you just see the message when you open the app or do a refresh

Are you referring to this in voip.ms's DID SMS settings? 
"URL Callback Retry: When selected, we will be expecting an "ok" output (without quotes) from your URL callback page as an indicator that you have received the message correctly. If we don't received the "ok" (without quotes) from your callback page, we will keep sending you the same message every 30 minutes."

If so, then what should it be set to?

The problem is the app thinks "You have no configured DIDs" - not that I have a configured DID that I'm not receiving SMSs on... I have refreshed and logged in/out many times.

**Comment by michaelkourlas** [comment]
This suddenly broke for me as well -- might be an API issue.

**Comment by dm17** [comment]
> This suddenly broke for me as well -- might be an API issue.

This is the app's sole functionality, as far as I know... Good to know. I tried to talk about support about it, but they just claimed this app is unofficial / unsupported.

**Comment by moreause** [comment]
dm17 the setting just before it  SMS URL callback   as to be set to  https://us-central1-voip-ms-sms-9ee2b.cloudfunctions.net/notify?did={TO}

and i set the sms sip account to primary

just did a test seem to be working for me

except the first time...but just upgraded to android 11  and  never turn on the app

**Comment by dm17** [comment]
> dm17 the setting just before it SMS URL callback as to be set to [https://us-central1-voip-ms-sms-9ee2b.cloudfunctions.net/notify?did={TO}](https://us-central1-voip-ms-sms-9ee2b.cloudfunctions.net/notify?did=%7BTO%7D)
> 
> and i set the sms sip account to primary
> 
> just did a test seem to be working for me
> 
> except the first time...but just upgraded to android 11 and never turn on the app
> 
> ![image](https://user-images.githubusercontent.com/36383877/92647430-dda80580-f2b5-11ea-8dd3-b00fdb106c1e.png)

Where were these instructions originally from? I feel strange about adding this URL not managed by me or voip.ms into my account. Who owns/runs that URL?

**Comment by moreause** [comment]
was in the wiki somewhere

without it i was able to retrieve the message when i opened the app but was not getting any signal a message was in if the app was not open

I,m no pro from what i remember it as to to with the push service

**Comment by michaelkourlas** [comment]
us-central1-voip-ms-sms-9ee2b.cloudfunctions.net is my push notifications server. You don't have to use it, but you won't get any push notifications. See the [documentation](https://github.com/michaelkourlas/voipms-sms-client/blob/master/HELP.md) for details.

**Comment by michaelkourlas** [comment]
"sms_available" was removed from the getDIDsInfo API call. It's a bug on their end.

**Comment by michaelkourlas** [comment]
Will update when I get a response.

![image](https://user-images.githubusercontent.com/1672388/92657413-c91e3a00-f2c2-11ea-8679-c1e7acfa5140.png)

**Comment by Adriel-M** [comment]
@michaelkourlas do you still need to check `sms_available`?

Do you remember the intent behind: https://github.com/michaelkourlas/voipms-sms-client/commit/a2b4469b80ef1961111b150603fa18851b2a2482

**Comment by michaelkourlas** [comment]
Unfortunately, I don't, but in any event I'd rather they fix their API. They can't provide an official API and then make backwards-incompatible changes like this.

**Comment by mjansen1972** [comment]
Mine broke too. Asking support from voip.ms they keep telling my to take it up with micheal as the app is a third party thing. i keep telling them it's on their end. They are as helpfull as a door knob,I don't like the blame shift towards micheals app. 
Hoping this gets solved as i do all my business via text(we sell raw dogfood) and now i'm missing orders.

**Comment by michaelkourlas** [comment]
If you contact VoIP.ms, don't say "there's a problem with VoIP.ms SMS". 

Say "the getDIDsInfo call used to return an attribute called "sms_available", but it has since been removed -- this is a backwards incompatible change, please add it back".

**Comment by mjansen1972** [comment]
> 
> 
> If you contact VoIP.ms, don't say "there's a problem with VoIP.ms SMS".
> 
> Say "the getDIDsInfo call used to return an attribute called "sms_available", but it has since been removed -- this is a backwards incompatible change, please add it back".

Done,hope it helps.

**Comment by mjansen1972** [comment]
Their reply:
Hello Martino,

Could you please provide further information regarding the information you're referring to, and if is this related to our API.

Please advise,
Regards.

**Comment by JohnMertz** [comment]
@mjansen1972 

I'm dealing with this with a CLI API library I'm working on as well. Here's a redacted response to the getDIDsInfo method:

`{"status":"success","dids":[{"did":"1234567890","description":"Text","routing":"account:123456","failover_busy":"none:","failover_unreachable":"none:","failover_noanswer":"none:","voicemail":"0","pop":"54","dialtime":"60","cnam":"1","e911":"0","callerid_prefix":"","note":"","billing_type":"1","next_billing":"2020-09-11","order_date":"2019-12-30 13:36:37","reseller_account":"0","reseller_next_billing":"0000-00-00","reseller_monthly":"0.00000000","reseller_minute":"0.00000000","reseller_setup":"0.00000000","sms_enabled":"1","sms_email":"email@domain.com","sms_email_enabled":"1","sms_forward":"","sms_forward_enabled":"0","sms_url_callback":"","sms_url_callback_enabled":"1","sms_url_callback_retry":"1"}]}`

Note that 'sms_available' is no longer provided. This has always been provided previously and is mentioned in the official documentation still: https://voip.ms/m/apidocs.php

I 'fixed' it by just checking if the it is sms_enabled is defined since it is not returned if the DID doesn't support SMS. But @michaelkourlas is right that they should fix the backwards compatibility, especially if it's still officially documented.

**Comment by mjansen1972** [comment]
> 
> 
> @mjansen1972
> 
> I'm dealing with this with a CLI API library I'm working on as well. Here's a redacted response to the getDIDsInfo method:
> 
> `{"status":"success","dids":[{"did":"1234567890","description":"Text","routing":"account:123456","failover_busy":"none:","failover_unreachable":"none:","failover_noanswer":"none:","voicemail":"0","pop":"54","dialtime":"60","cnam":"1","e911":"0","callerid_prefix":"","note":"","billing_type":"1","next_billing":"2020-09-11","order_date":"2019-12-30 13:36:37","reseller_account":"0","reseller_next_billing":"0000-00-00","reseller_monthly":"0.00000000","reseller_minute":"0.00000000","reseller_setup":"0.00000000","sms_enabled":"1","sms_email":"email@domain.com","sms_email_enabled":"1","sms_forward":"","sms_forward_enabled":"0","sms_url_callback":"","sms_url_callback_enabled":"1","sms_url_callback_retry":"1"}]}`
> 
> Note that 'sms_available' is no longer provided. This has always been provided previously and is mentioned in the official documentation still: https://voip.ms/m/apidocs.php
> 
> I 'fixed' it by just checking if 'sms_enabled' is defined since it is not returned if the DID doesn't support SMS. But @michaelkourlas is right that they should fix the backwards compatibility, especially if it's still officially documented.

Bit over my head,lol. So as it stands by them removing the "sms_available" it broke our beloved app from michael? 
Are we waiting for them to reinstate that or are we looking for a solution in the app to bypass that? (with we I mean you smarter then me persons :). )   
Also new to this guthub thing,this post is now closed?

**Comment by michaelkourlas** [comment]
I was going to wait until MMS support could be added to release 0.6.6, but I guess I'll be releasing it early.

**Comment by dm17** [comment]
Great, so new release on F-Droid can happen now?

**Comment by michaelkourlas** [comment]
Not quite yet, but soon.

**Comment by mjansen1972** [comment]
Updated the app and my phone with a freshly installed app works great, No more spamming black bar saying it cant sync as voip.ms is unavailable either !  Thank you so much for the quick actions :)

**Comment by dm17** [comment]
They fixed the API upon request. I did not update the voip.ms SMS app because there isn't a new one in F-DROID yet - however, the existing app started working with voipms's API fix. @michaelkourlas 
Thanks.
