### ISSUE TITLE
Konvert CustomApplication

### ISSUE THREAD

**Issue by Adriel-M** [michaelkourlas/voipms-sms-client#216]
Any value on converting this file so we can get a complete kotlin app?

Was trying to trace why it was still in java and saw https://github.com/michaelkourlas/voipms-sms-client/blob/4f3fc298092bb2c74ea8037bfa208f8ba91663eb/voipms-sms/src/main/kotlin/net/kourlas/voipms_sms/CustomApplication.java#L46

I ran a6317460a2e089e67e7426ec910fa3fab546d841 against `Nexus 4 API 22` and the app wouldn't even open.

I converted it here https://github.com/Adriel-M/voipms-sms-client/commit/acfd5cb208f564fb0df9ec9c14256ff67a435e5f and the app opens again. Just wondering, what other problems were you seeing?

**Comment by michaelkourlas** [comment]
I don't really recall, unfortunately, but I don't want to fix what isn't broken :P

I can live with a single class in Java.

**Comment by michaelkourlas** [comment]
I just tested a converted version with the API 21 emulator and it seems to work.

**Comment by michaelkourlas** [comment]
Maybe the problem was ICS.
