### ISSUE TITLE
User Android Identity Profile to Populate Image of Phone Owner

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#22]
Currently the app uses the address book to populate the images of the person your'e talking to, however the image for yourself (the phone owner) is always blank.

This can be rectified by adding ones self to the address book, however the app should simply use the identify profile to do this.

**Comment by michaelkourlas** [comment]
I've always added myself to the phone book :P

However, using the identity profile is probably a better idea. I'll see what I can do.

**Comment by michaelkourlas** [comment]
This has now been implemented.
