### ISSUE TITLE
Import Phone Number from SMS

### ISSUE THREAD

**Issue by Ichijin0** [michaelkourlas/voipms-sms-client#222]
When tapping on a phone number that was sent to me in an SMS, my phone would bring me to a lost of apps to import the number to call.  I was wondering if VoIP.ms SMS could be added to that list of apps so that the number gets imported into Voip.ms SMS and can text it right away.

The SMS that I wanted to do this in was had a bunch of text in the same message and I don't have a quick way of just copying the phone number to my clipboard without all the other text.

**Comment by michaelkourlas** [comment]
I suspect this won't be possible for the same reasons discussed in #49.

Do you know of a specific Android intent that apps can listen to that would get you this behaviour without having to be the default SMS app?
