### ISSUE TITLE
Notification does not completely clear after being dismissed

### ISSUE THREAD

**Issue by kevingatera** [michaelkourlas/voipms-sms-client#224]
.Eg: after pressing "mark as read"Device used:Oneplus 7TAndroid: 10 and 11 (same behavior) 

![Screenshot_20210127-215846.jpg](https://user-images.githubusercontent.com/22301610/106088437-f34a8a00-60f3-11eb-87ee-ea8db5268c5f.jpg)

**Comment by xenophane** [comment]
Same here with a Pixel 3 XL on Android 11.

**Comment by michaelkourlas** [comment]
I think this might be the group notification -- it's not being correctly dismissed. Will investigate.
