### ISSUE TITLE
Feature request: Mark all as read

### ISSUE THREAD

**Issue by Tin-man-0** [michaelkourlas/voipms-sms-client#232]
Just wanted to put in a request to be able to mark all unopened or unread messages as opened or read. There's no folders or organization in this app so just being able to mark individual DIDs as read would be sufficient I think. 

Another feature that would be great, but it's low priority i think but being able to assign contacts into groups and assign different notification sounds or screen flashing yellow allert type thing depending on who messaged.

**Comment by michaelkourlas** [comment]
(1) You can already do this by selecting all of the conversations and clicking "mark read".

(2) Google Messages doesn't have that feature, and I think it's unlikely I'll add it too. You can already set custom notifications for particular conversations.
