### ISSUE TITLE
Registration status display

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#24]
It would be helpful if there was a screen available to show what the current GCM registration status is and force it to re-register when the registration is lost. There have been cases where this was what happened, but there was no way for the user to confirm; the user only knows because new messages were not being signalled or because we were receiving  the same message multiple times due to the server retry.

**Comment by fcastilloec** [comment]
Good idea, just not sure how and where to display the registration status.

**Comment by michaelkourlas** [comment]
My understanding is that GCM registration should never be lost. If it is, that means that I implemented it incorrectly. I think I may have used an older version of the GCM docs by mistake. I'll see if I can fix it.

**Comment by michaelkourlas** [comment]
I've re-implemented GCM using the new API. There's a new listener that re-registers for GCM automatically when Google wants to refresh tokens. This should fix any problems relating to lost registration.
