### ISSUE TITLE
Refresh animation freezes on Android 12

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#241]
Hi!

I'm using the F-droid variant of the app, on LineageOS 19 (Android 12) on a Pixel 3a phone.

When I refresh the app manually by scrolling down, the refresh animation shows the circle+arrow logo and everything works properly (goes down, goes back up) until it changes to a small line and stays like this until the refresh is done, then disappears. IIRC, this animation used to be more fluid on Android 11, so maybe something changed?

I'm attaching a GIF of what happens, with a pretty low framerate and badly pixelized :) It's not great, but I think it's enough for you to understand the problem? If not, I can send you a proper screen capture in private.

![voipms](https://user-images.githubusercontent.com/6070749/169885405-5f46e4da-eff0-43ba-ac62-fd8ba5f3bfdd.gif)

Obviously, this issue is pretty low priority :)

**Comment by michaelkourlas** [comment]
My device is running Android 12. Unfortunately, when I install the F-Droid version of the app, I can't reproduce this -- the animation looks normal to me.

The functionality is provided by a support library class called `SwipeRefreshLayout`.
