### ISSUE TITLE
message never sent

### ISSUE THREAD

**Issue by yulman19** [michaelkourlas/voipms-sms-client#244]
Sometimes, I type a message and I click send and it stays in a "sending" status, but is actually never sent; it stays visible as "sending". I have to copy then delete it and resend again. Seen the behavior on Android 11 and 12.

**Comment by xenophane** [comment]
This happens occasionally to me as well.

**Comment by michaelkourlas** [comment]
There was a bug that could result in message send attempts being lost if a previous one failed, but it was [fixed](https://github.com/michaelkourlas/voipms-sms-client/commit/942f9d883e89aeee729ad0cd111c8f5d3e3121e7#diff-93fe9b1af13c5c6892c58afff4cc49930a0f613b84911adb6d8a705626727ab2) in 0.6.22.

When you send a message, it gets enqueued as an [expedited work request](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work#expedited) using WorkManager. However, Android enforces execution quotas, so it may be downgrading the work request to a non-expedited request and deferring it for later.

**Comment by yulman19** [comment]
Not to contradict you but I'm always on the latest version and I believe it still happens. thanks for your work.

**Comment by michaelkourlas** [comment]
Oh, I believe you. I was theorizing that this may be the result of Android de-prioritizing the send message request. It could also be a real bug, but unfortunately without a repro recipe it's tough to investigate and fix. I don't really use the app myself anymore, and haven't for many years -- I just maintain it.

**Comment by michaelkourlas** [comment]
If you can provide a consistent repro recipe, let me know and I'll see if I can repro on my device.

**Comment by yulman19** [comment]
you're the man, seriously, maintaining something you don't use is appreciated devotion.
