### ISSUE TITLE
Removed DID causes client to not retrieve messages

### ISSUE THREAD

**Issue by GeNTooGeek** [michaelkourlas/voipms-sms-client#248]
I recently noticed that the app was no longer downloading new messages. When opening the app, an error message would indicate that there was an invalid DID. I am sorry, I don't have the exact error message; I am willing to recreate the issue, if you need.

After some thought, I remembered that I had removed some of my DIDs from my VOIP.ms account. When I looked in the settings, sure enough one number was listed as being stored locally, but not found in the VOIP.MS account. As soon as I disabled the number in settings, the app downloaded the months worth of messages that I had been neglecting.

It seems that even if one of the DIDs was invalid, the sync for the rest of the numbers should continue.

**Comment by michaelkourlas** [comment]
I agree we can probably do better here.
