### ISSUE TITLE
Implement per-contact notification settings

### ISSUE THREAD

**Issue by bravo90078** [michaelkourlas/voipms-sms-client#25]
This is a superficial request and very low priority, but the ability to alter/assign colors to each contact would be helpful from an organization standpoint.

**Comment by michaelkourlas** [comment]
I'll see what I can do, though as you pointed out it is a low priority feature.

**Comment by michaelkourlas** [comment]
Consolidating with per-user notification settings.

**Comment by michaelkourlas** [comment]
Will add support for this once Android O is released.

**Comment by michaelkourlas** [comment]
This has been implemented and will be in 0.6.0.

Material design style colours for contacts without a contact image were implemented in a prior release. I will open a separate issue for the ability to assign colours to contacts.
