### ISSUE TITLE
Set as default sms app

### ISSUE THREAD

**Issue by dsivasuthan** [michaelkourlas/voipms-sms-client#250]
This is the only sms I use. Is it possible to add an option to make this the default sms client for android?

**Comment by dsivasuthan** [comment]
Looks like there has been discussion in issue #49. I am not sure if there has been any progress on this. I could help out with coding it if a PR would be considered to be merged.

**Comment by michaelkourlas** [comment]
As mentioned, this is a duplicate of #49. There are no plans to add carrier SMS support to the app, and in general I do not accept PRs.
