### ISSUE TITLE
Please remove Google Tracking (Crashlytics, Firebase) from F-Droid App

### ISSUE THREAD

**Issue by ttffm** [michaelkourlas/voipms-sms-client#256]
Is there any way you can please remove these trackers from the F-Droid version of the app out of concern for privacy and to avoid Google data collection as much possible?

**Comment by michaelkourlas** [comment]
The F-Droid version does not contain any Firebase code.

**Comment by ttffm** [comment]
Unless, I am missing something, exodus shows these trackers.
![Screenshot_2023-09-06_10-46-37](https://github.com/michaelkourlas/voipms-sms-client/assets/99693930/999e0ead-fc8e-41b2-9659-b6d343afb1d1)

**Comment by michaelkourlas** [comment]
The version published on F-Droid is fine. 

![Screenshot_20230906_141336_Chrome](https://github.com/michaelkourlas/voipms-sms-client/assets/1672388/438ec0b7-5f93-4cfc-a9cb-82e3031a61de)

**Comment by michaelkourlas** [comment]
I think there may be some tracking code left in my own F-Droid builds, though. F-Droid builds them differently. To be safe, I'm just going to remove them.

**Comment by michaelkourlas** [comment]
I think there may be some Google/Firebase code left in my own F-Droid builds. I just disable some of the generated tasks, but F-Droid completely strips out the plugins.

What I've been doing may not be sufficient to disable the Google/Firebase code, so to be safe I am going to remove all of the F-Droid builds I've published.

I'm also going to see if I can change my build to strip out the plugins instead.

**Comment by ttffm** [comment]
Thank you. Looking forward to the updated version.

**Comment by michaelkourlas** [comment]
You can just download the latest version directly from F-Droid.

**Comment by michaelkourlas** [comment]
Actually, I think I may have jumped the gun. I tested my APK manually using exodusprivacy/exodus-standalone and it doesn't report having any tracking code either.

I can't really explain your results.
