### ISSUE TITLE
Bug-Messages getting stuck and not sending

### ISSUE THREAD

**Issue by thekofimensah** [michaelkourlas/voipms-sms-client#259]
Hi, I've been noticing this behavior for a couple of years now but I think I'm able to reproduce it.

I'm on a Pixel 7, up to date android version.

When I send a message and immediately after I press the back arrow to go to another message, the message gets stuck in the "Sending..." state and doesn't ever send the message. I feel like it also sometimes when I exit the app quickly, but I can't reproduce that.

Any idea of why this could be happening?

**Comment by thekofimensah** [comment]
Duplicate

**Comment by yulman19** [comment]
that was quick
