### ISSUE TITLE
Publish release on Google Play

### ISSUE THREAD

**Issue by fcastilloec** [michaelkourlas/voipms-sms-client#26]
It would be great if the latest version could be publish on the Play store, this will make it available to more users and easier to find and track any new bugs that might crop.
If you think the final product is not up for final release, maybe a suggestion of creating a Beta channel so at least some user can test the app and report bugs.

**Comment by michaelkourlas** [comment]
Done! There's probably plenty of bugs, so keep those issues flowing! :)
