### ISSUE TITLE
How to get SMS notifications with the app instead of other app

### ISSUE THREAD

**Issue by balz666** [michaelkourlas/voipms-sms-client#269]
I use Zoiper for phone and VOIP.ms for SMS. When there was the bug with VOIP.ms I uninstalled it, but then reinstalled it. Since I reinstalled it, I don't get any notification when there is a SMS in VOIP.ms but get the notification in Zoiper, which is annoying, because I want to reply by using VOIP.ms and the notification screen with VOIP.ms used to give an idea of what the SMS was about. I tried many options, but wasn't able to solve this issue. Thanks

**Comment by michaelkourlas** [comment]
Please make sure:
* notifications are enabled for the app in the Android system settings
* the push notifications callback is correctly configured; see the app's help for instructions

**Comment by balz666** [comment]
> Please make sure:
> 
> * notifications are enabled for the app in the Android system settings
> * the push notifications callback is correctly configured; see the app's help for instructions

Thanks... Notification is on in Android for the three options, yet I still get a notification throught Zoiper and not VOIP.ms when a SMS arrives...

Do you have a link for that "push notification callback" thing? I don't know where to look for. Thanks

**Comment by balz666** [comment]
OK I tried to click "synchronization" and now I received a notification once, but still receive on the other app as well. I'll need to find a way so Zoiper stops managing my SMS and I'm not sure yet VOIP.ms is reliable enough for the notifications.
