### ISSUE TITLE
Deleting messages from server

### ISSUE THREAD

**Issue by repunset274** [michaelkourlas/voipms-sms-client#272]
Hello, greatly appreciate your app!! My question is, how does one go about deleting messages from the server?

I can delete the whole database within the app, but then when I swipe down the app pulls all the messages again (based on the synchronization start date). Ever since I began using the app, the SMS messages do not show up in the SMS/MMS center in voip.ms webpage either, so I cannot delete them that way either.

**Comment by michaelkourlas** [comment]
The app no longer supports deleting messages from the server.
