### ISSUE TITLE
Sync failed: corrupt response

### ISSUE THREAD

**Issue by zlehnherr1** [michaelkourlas/voipms-sms-client#274]
Title is the error I get, I believe that I saw a reddit post about VoIP.ms changing something with their api.

**Comment by auralius-dev** [comment]
I get this error too, when waiting to receive messages. I can send them just fine. First time user of this application, since five minutes ago.

**Comment by michaelkourlas** [comment]
Duplicate of https://github.com/michaelkourlas/voipms-sms-client/issues/273 - please see that issue for a workaround.
