### ISSUE TITLE
Desktop version?

### ISSUE THREAD

**Issue by bogen85** [michaelkourlas/voipms-sms-client#276]
I've not looked too deep into the source code of `voip-sms-client`.

I use it a lot on Android, but would it would nice if ran on the desktop as well.

How coupled is this with android in terms of UI and underlying OS support?

What kind of undertaking would be involved in a desktop port to something like [QtJambi](https://github.com/OmixVisualization/qtjambi) (Which also runs on Android, but runs on Linux, Apple, and Mac Desktops as well)?

**Comment by yulman19** [comment]
You can run on windows with Windows subsystem for Android

**Comment by bogen85** [comment]
Not on Windows. On Linux Waydroid and Android VMs are extremely awkward solutions. Waydroid has potential, but if you are not on Wayland it is extremely complicated.

**Comment by bogen85** [comment]
> You can run on windows with Windows subsystem for Android

I do not use Windows, so not an option for me.

On Linux Waydroid and Android VMs are extremely awkward solutions.

Waydroid has potential, but if you are not on Wayland it is not as straight forward, especially if you running in a VM.

While on Windows with the subsystem for Android the setup might be more straight forward, from what I've read up on that, the end result is basically the same as one what would get a on Linux. Yes, the app runs, but the experience using it is not great as it is not integrated which ones native environment.

**Comment by michaelkourlas** [comment]
Unfortunately I'm not willing to put the effort in to make a desktop port.

The app's open source, so the code's there if you want to use any of it in your own attempt.
