### ISSUE TITLE
Text messages containing non-ASCII characters are mangled

### ISSUE THREAD

**Issue by michaelkourlas** [michaelkourlas/voipms-sms-client#28]
Unfortunately, this looks like a problem with VoIP.ms; there's nothing I can do on this end.

**Comment by michaelkourlas** [comment]
It looks like I might have been wrong about this, given that there is another VoIP.ms SMS app (VOIP2SMS) that supports non-ASCII characters. Further investigation is warranted.

**Comment by michaelkourlas** [comment]
As far as I can tell, VOIP2SMS can only receive non-ASCII characters, not send them. Even so, I have no idea what sorcery it's using to do that. Neither the SOAP nor REST APIs for the getSMS API call will produce these characters; they're always appear as a question mark. I tried multiple encodings to parse the results; that didn't work either.

**Comment by michaelkourlas** [comment]
I'm going to close this again for now; if anyone can figure out why VOIP2SMS is able to do this, please let me know!

**Comment by fcastilloec** [comment]
The only way that I've be able to receive non-ASCII characters has been through Gmail. If you forward your messages to an email address, you'll be able to see those characters. It's not just VOIP2SMS, Gmail also does it. There has to be a way this characters are being received properly

**Comment by michaelkourlas** [comment]
Try using the REST API and see if you get any non-ASCII characters:

https://voip.ms/api/v1/rest.php?api_username=<USERNAME>&api_password=<PASSWORD>&method=getSMS&did=<DID>

**Comment by michaelkourlas** [comment]
Confirmed that you can't send non-ASCII characters through VoIP.ms by email either, but that you can receive them.

**Comment by michaelkourlas** [comment]
Oh, I think I figured it out! VOIP2SMS's callback URL includes the message, so it's probably taking the message directly from the URL, not the API. I guess the API is broken but the callback URL isn't, for some reason.

**Comment by michaelkourlas** [comment]
I'm not going to change the callback mechanism for privacy reasons; it's up to VoIP.ms to fix their API.

**Comment by LouisStAmour** [comment]
I can confirm that while the Rest API returns ""Testing special characters ?????????߬??????"", the Web UI and Soap interface (XML) return: "Testing special characters ¶£§?ª®éå®?ß¬?ª?®º?"

Now, I'm pretty sure the ?s weren't there originally, but this is a lot closer to expected behaviour. Not sure you'd want to switch from Rest to Soap, however.

**Comment by HarryPehkonen** [comment]
The REST API appears to show Unicode characters now (escaped per the spec at json.org).  Example via cURL: "message":"h\u00e8llo"

**Comment by bohemier** [comment]
Perhaps this big should reopened in the light of HarryPehkonen's comment?

**Comment by michaelkourlas** [comment]
Last I checked it only seemed to properly encode a subset of Unicode characters. I'll take another look.

**Comment by bohemier** [comment]
If it could at least encode accented characters (such as é è à ç), that would be a good start. Thanks for looking into this!

**Comment by michaelkourlas** [comment]
It looks like it's encoding some unicode characters properly now; more than it used to, at least. This doesn't require any changes to the app, since the JSON parser will convert them if they're properly encoded.
