### ISSUE TITLE
Incoming message doesn't appear when in conversation

### ISSUE THREAD

**Issue by aurelius99** [michaelkourlas/voipms-sms-client#29]
EDIT: this issue happened with the push notifications option enabled, BUT the url callback wasn't configured!  It works fine after I configured the url callback.
**************
When I am viewing a conversation, new incoming messages aren't displayed until I exit and reenter the conversation.
When I'm at the upper-level view (showing the most recent message from all contacts), incoming messages appear instantaneously.

**Comment by michaelkourlas** [comment]
I can't reproduce this problem, but I'm presently using an unreleased version. If this issue is still present in the next release, open the issue again.
