### ISSUE TITLE
Provide the option to set the URL callback automatically from settings

### ISSUE THREAD

**Issue by fcastilloec** [michaelkourlas/voipms-sms-client#30]
Voip.ms API has a function that lets you set the URL callback. It's part of the setSMS function, here's a snip from their API:

**setSMS**

setSMS | :
------------ | -------------
did *[Required]* | DID to be Updated (Example: 5551234567)
enable *[Required]* | Enable/Disable the DID to receive SMS Messages (Values:1=Enable / 0=Disable)
url_callback_enable | If Enable, SMS Messages received by your DID will be send a GET request to the URL callback provided (Values:1=Enable / 0=Disable)
url_callback | SMS Messages received by your DID will be send a GET request to the URL                                 callback provided. Example: http://mysite.com/sms.php?to={TO}&from={FROM}&message={MESSAGE}
url_callback_retry | Enable URL callback Retry (Values:1=Enable / 0=Disable)
                             |   we will be expecting an "ok" output (without quotes) from your URL callback page as an indicator that you have received the message correctly. If we don't receive the "ok" letters (wihtout quotes) from your callback page, we will keep sending you the same message every 30 minutes.

Setting this up directly from the Settings will improve the overall experience. It can be a text field  automatically populated with @michaelkourlas server URL and that the user can just edit to set it to its own server. Or it can be a simple button or check-mark that sets the URL to @michaelkourlas server without any user input.
The app could also check if there's a URL callback address set and enabled (with the getDIDsInfo function that the *showSelectDidDialog* function already uses). This way the app provides an error if push notification has been enable but no URL has been set.

**Comment by michaelkourlas** [comment]
Wow. I had no clue about this. This is an excellent idea.

**Comment by michaelkourlas** [comment]
Implemented.
