### ISSUE TITLE
add "reply" support to notifications - for Android Wear + other apps to programmatically reply.

### ISSUE THREAD

**Issue by DER31K** [michaelkourlas/voipms-sms-client#34]
Currently, when a voip.ms SMS is received a notification is created on the device that features nice quick reply/archive buttons. However, these buttons are practically useless on my Android Wear watch because the reply feature requires grabbing my phone to type... as opposed to simply speaking my reply to my watch.

I have considered creating my own workaround using AutoNotification and Tasker to listen for voip.ms SMS notifications.

But I believe it would be relatively easy for you to add a reply field to the notification and/or improved Wearable notifications. I believe it's has recently been added to the API and several other communications apps have already done so, (its kind of becoming the standard)

I found some more information here:
http://www.plotprojects.com/whats-new-in-android-notifications/

No rush - thanks for the great app!

**Comment by michaelkourlas** [comment]
This should be relatively straightforward.

**Comment by michaelkourlas** [comment]
Support for this has been added to 0.5.0, which should be released soon.
