### ISSUE TITLE
Please publish on F-Droid 

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#36]
WOW. Thanks for this app. I was impressed when I saw it, but even more when I saw it was free software.

You should definitely publish it on F-Droid to make it available for people not wanting to use Google Play:

https://f-droid.org/wiki/page/Inclusion_Policy
https://f-droid.org/wiki/page/Inclusion_How-To

**Comment by jcharaoui** [comment]
+1

**Comment by michaelkourlas** [comment]
There's really not much point in publishing the app on F-Droid, as it relies on GCM, which in turn requires Google Play services, which in turn means you have Google Play installed.

**Comment by dkisselev** [comment]
<not familiar with specific of how Android apps talk to Google Play Services>

Wouldn't the apk crash/be unhappy when it tries to configure itself with Play Services as it installs/runs? Or does GPS work on a pub/sub model that doesn't blow up if play services isn't available?

**Comment by michaelkourlas** [comment]
Not unless you enable notifications, which are disabled by default. Then it'll continuously ask you to install Google Play Services. I don't believe the app will crash, though.

**Comment by anarcat** [comment]
one advantage of putting this on f-droid (compared to using the releases section) is that you can get automatic updates. also, if we can turn off push notifications and google play services integration (#37), then it becomes really useful to use this app directly from f-droid.

**Comment by anarcat** [comment]
oh, and for the record, the releases tab doesn't show up on Android 5.1's web browser (mobile or desktop version) nor through the github client app, at all. not sure why, and this is obviously not your fault, but it does make this thing harder to install.

**Comment by anarcat** [comment]
followup on f-droid's side: https://f-droid.org/forums/topic/voip-ms-sms/

**Comment by michaelkourlas** [comment]
I'll create an F-Droid compatible version this summer as part of the v0.4.2 release.

**Comment by michaelkourlas** [comment]
All right, there's now a purely FOSS build in the fdroid branch.

**Comment by michaelkourlas** [comment]
The F-Droid password reset mechanism is broken, so I can't log in to update the inclusion thread for VoIP.ms SMS. Can somebody else do that?

**Comment by anarcat** [comment]
@michaelkourlas just did that, thanks for the followup!!!

**Comment by anarcat** [comment]
and now of course the question is how to get realtime notifications without GCM :) followup on #37  for that. #77 may be a solution.

**Comment by michaelkourlas** [comment]
Confirmed that the app is available on F-Droid.

**Comment by anarcat** [comment]
for me, the app is signed with a different key, i assume this is normal?

**Comment by baldurmen** [comment]
F-droid builds & signs with it's own key. That key is different from
@michaelkourlas's one, so I guess the answer would be yes.
