### ISSUE TITLE
Messages with quotes show escape characters 

### ISSUE THREAD

**Issue by warpzero** [michaelkourlas/voipms-sms-client#38]
When receiving a message with " or ' characters, I'm seeing them escaped as follows:

But of course \"I don\'t know!!\" Is my official answer

As you can see, the \ escape character is displayed in the UI.

**Comment by jeanfmartel** [comment]
It seems the problem originates from Voip.ms server.  The JSON reply inserts two escape characters instead of one... i.e.: \\' instead of \'.  I circumvented the problem by hardcoding a filter but I suppose the problem will be fixed by voip.ms sometimes.

**Comment by warpzero** [comment]
Great! Thank you very much for the quick response.

**Comment by philoconr** [comment]
Can/will this hardcoded filter be implemented in the next release?

**Comment by jeanfmartel** [comment]
I could send you my .apk implementing the filter.  There are also some other improvements including some quick optimizations to decrease lag for long conversations

**Comment by philoconr** [comment]
I would love that! Currently been deleting my message threads to try and
keep it running optimally. Can you post a dl link?

**Comment by jeanfmartel** [comment]
Here it is.
https://drive.google.com/file/d/0BzIzeNSmO_f9d3NlMkVEN3ZISDQ/view?usp=sharing

**Comment by michaelkourlas** [comment]
@jeanfmartel, would you mind submitting a pull request with your changes?

**Comment by jeanfmartel** [comment]
@michaelkourlas, Gladly!  I created the pull request.  It's my first contribution on GitHub so I hope I did everything correctly.

**Comment by michaelkourlas** [comment]
Thanks! I'll take a look.

**Comment by HarryPehkonen** [comment]
At this time (2015-12-12), the Voip.ms API method getSMS does not appear to double-escape (via cURL):  "message": "\"Abc\" 'def' ghi"

**Comment by michaelkourlas** [comment]
Confirmed. The filter is no longer necessary.
