### ISSUE TITLE
Slashes for apostrophe

### ISSUE THREAD

**Issue by philoconr** [michaelkourlas/voipms-sms-client#40]
For regular sms messaging when ever an apostrophe gets sent it will always display in the textbox as " \' " . Seems to be received fine on the other end. This affects both incoming and outgoing message displayed through the app. 

Hope fully there is some easy fix for this. Really love this app, great work michael.

**Comment by dkisselev** [comment]
Did you intend to close the issue? Closing it means that it's been fixed or isn't relevant anymore.

**Comment by philoconr** [comment]
I noticed a duplicate issue had already been posted. I did not see a simple
delete button.

Is this appropriate?

Thanks
