### ISSUE TITLE
Voicemail voice-2-text

### ISSUE THREAD

**Issue by thejinx0r** [michaelkourlas/voipms-sms-client#41]
I've been using this app now and it's working really well.
I was thinking of integrating a feature where the app would be able to fetch the voicemail, and having it be able to transcribe the voicemails to text.

I'm currently thinking of using IBM's voice transcription. 

Do you have any thoughts on this?

**Comment by dkisselev** [comment]
This is probably something that we would want to roll into the server app because otherwise you're using twice the mobile bandwidth (download the audio then upload it to whatever cloud recognizer).

I would be highly interested in the feature though.

**Comment by thejinx0r** [comment]
I don't disagree with the doubled amount of bandwidth.

The main reason for having it on the client side is so that each user can create their own API access tokens. With IBM's service, there's only 1000 minutes per month free and then it's 2 cents per minute. 

I don't know how the main developer (@michaelkourlas) want to handle this issue of charging users for it. 
Or even if that's something that michael would want to handle himself.

**Comment by thejinx0r** [comment]
I hadn't noticed the code for the server published.
I could definitely write something for the server side, but it will definitely be up to @michaelkourlas for the final decision.

**Comment by michaelkourlas** [comment]
I think it's best if this app sticks to dealing with SMS messages exclusively. Feel free to create your own voicemail-to-text app, though!
