### ISSUE TITLE
Timezone is wrong due to daylight savings time change

### ISSUE THREAD

**Issue by ultramancool** [michaelkourlas/voipms-sms-client#43]
All my times are showing up off by an hour, I think the problem originates here:

https://github.com/michaelkourlas/voipms-sms-client/blob/df6b974aac5c29cb30f36bc7b63cb9ff398c5c49/voipms-sms/src/main/java/net/kourlas/voipms_sms/Database.java#L497

Where -5 is used for the timezone offset while currently it's -4 I believe.

**Comment by michaelkourlas** [comment]
Hmm, this should have been fixed. See here: https://github.com/michaelkourlas/voipms-sms-client/issues/35

**Comment by ultramancool** [comment]
Ah, I'm on an outdated version. sorry about that, I'll try an update
shortly, go ahead and close this.
