### ISSUE TITLE
Add a way to donate

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#45]
I really like this app and see a great potential in it. Since I don't feel like I can hep out sending pull request (I'm no Android dev), I'd like to donate some money to help you out.

Do you think you could add a Donate button in your README.md and on Google Play?

**Comment by michaelkourlas** [comment]
I can certainly add a donate button to the readme! Google Play has some pretty strict rules about payments using systems other than the Play in-app payment system, though.

**Comment by michaelkourlas** [comment]
All right, there are now a couple of options:
* Google Play in-app purchase
* Link to PayPal donation page
