### ISSUE TITLE
Add support for multiple DIDs

### ISSUE THREAD

**Issue by ginsu0** [michaelkourlas/voipms-sms-client#46]
It would be useful for some of us that rely on SMS from multiple DIDs. Maybe it can be implemented as a drop-down box on the main screen, for the ability to switch quickly between them? If there is a worry about cluttering the interface, perhaps the drop-down could appear dynamically if more than one SMS-enabled DID is detected on the account? How difficult of a change do you expect this would be?

**Comment by flord** [comment]
+1

**Comment by alanchau** [comment]
+1

**Comment by maneamarius** [comment]
+1

I'd love to see this feature implemented

**Comment by michaelkourlas** [comment]
I'll look at this in the 0.5.0 release.

**Comment by bohemier** [comment]
This would be a big improvement... thanks

**Comment by demonicpancake** [comment]
+1

**Comment by bellmork** [comment]
plus one hundred

**Comment by schultzter** [comment]
I use one DID on one phone and a different DID on another phone but they are both in the same VoIP.ms account. Can I get push notifications for both? It wasn't working the other day, I only got push notifications for the one most recently set up.

**Comment by michaelkourlas** [comment]
No, you can't at the moment. This will hopefully change soon.

**Comment by lazuratus** [comment]
+1

**Comment by michaelkourlas** [comment]
Support for this has been added to 0.5.0, which should be released soon.
