### ISSUE TITLE
No way to set the VoIP.ms SMS client as the default SMS client

### ISSUE THREAD

**Issue by aberios** [michaelkourlas/voipms-sms-client#49]

**Comment by michaelkourlas** [comment]
This isn't possible, as VoIP.ms SMS isn't an SMS client in the strictest sense. It's not capable of sending and receiving SMSes through your carrier's network.

**Comment by anarcat** [comment]
that shouldn't be a problem: Signal sets itself up as a SMS app, yet it sends and receives text messages through a custom data protocol. it would be nice to setup this app to pop open when i send a text message to someone in my contacts.

right now, usability could be improved: if i want to send a text message to someone in my list of contacts, i can't do it from my contacts app. i need to remember to go in the VoIP SMS app, click the little `(+)` sign and find the contact again...

It would be great if this could be hooked in as a regular SMS app for folks like us that don't actually have carriers. :)

**Comment by michaelkourlas** [comment]
Just for the record: https://github.com/michaelkourlas/voipms-sms-client/issues/55#issuecomment-205887682

**Comment by anarcat** [comment]
well, the comment in #55 explains how it's tricky to talk to another third party SMS provider, but it doesn't explain why it's not possible for VoIP.ms to set itself up as the default SMS provider. for me, that would still be a good thing, since it would allow me to send a text to someone from the contact list directly.

**Comment by michaelkourlas** [comment]
Well, in order to do that, my understanding is that VoIP.ms SMS would have to be capable of sending/receiving messages from your carrier. That would be very complicated and it's not really what this app is for.

**Comment by dkisselev** [comment]
@michaelkourlas, I see what he's saying, even though we're using a proprietary API to do any actual SMS transmission, apps can announce that they accept the SMS sending intent, so when you tap "Send a Message" in the contacts app, voipms-sms will grab that intent and start a message.

You don't need to actually send it over the cell networks, just accept the intent.

Here's an SO article listing the (convoluted) way you need to define the ability to handle SMS's in the manifest: http://stackoverflow.com/a/8698364 I'm sure many of those permissions would be removed to prevent Android from trying to send incoming SMS's to the app, but it should work for outgoing.

It also sounds like you technically can directly overwrite the SMS database, so incoming voipms-sms's appear in the global message db: http://android-developers.blogspot.ca/2013/10/getting-your-sms-apps-ready-for-kitkat.html

**Comment by anarcat** [comment]
> You don't need to actually send it over the cell networks, just accept the intent.

Exactly. Signal does that: it overrides the builtin SMS app. It imports the messages and incoming text messages are recorded in Signal and not in the SMS app anymore (for that you need carrier support, but they do it!). Outgoing text messages go through Signal as well (for that you *don't* need carrier support).

**Comment by michaelkourlas** [comment]
It sounds like it makes sense to include the following so that VoIP.ms SMS will appear as an option when trying to send an SMS:

````
<intent-filter>
    <action android:name="android.intent.action.SEND" />                
    <action android:name="android.intent.action.SENDTO" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="sms" />
    <data android:scheme="smsto" />
</intent-filter>
````

I think that's all that's really necessary, frankly. VoIP.ms doesn't need to be the "default" SMS app; the user just needs to be able to use VoIP.ms to send an SMS from another application.

**Comment by dkisselev** [comment]
I'm not sure if Android has an SMS "share to" style intent picker available by default, from what I've briefly read, you either define all the intents fully and Android makes you the default app, or you don't and Android ignores you.

But I'm sure you'll cross that bridge as soon as you get there, thanks for putting so much time into OSS and keeping this going!

**Comment by michaelkourlas** [comment]
@dkisselev, the second link you included suggests that's not the case

> In consideration of some apps that do not want to behave as the default SMS app but still want to send messages, any app that has the SEND_SMS permission is still able to send SMS messages using SmsManager.

This suggests that at least certain SMS features are available to apps that aren't the default for SMS. Hopefully the SMS sendto intent is one of those features as well.

**Comment by michaelkourlas** [comment]
After some experimentation, I have determined that the only way for an app to receive an SMS SEND_TO event is to be the default SMS app. As @anarcat points out, I could take the Signal approach and add support for standard SMS messages to the app. Unfortunately, that would necessitate re-writing significant portions of the app for comparatively little gain.  I certainly agree that it would be nice to be able to jump to VoIP.ms directly from the contacts screen, but personally I don't believe that not being able to do so is a particularly significant UI problem,

As such, I'm going to close this issue until Android permits apps to receive the SMS SEND_TO intent without providing all SMS services.

**Comment by theretohere** [comment]
Would making this app the default SMS app also make it accessible to the Google assistant? So you could request by voice to send a text message to any contact, just like the native built in android messages app?

eg. Today in the car I needed to send a text message, so I said, "Ok Google, send a text message to Yoda." "The force is with you." "Send". 

But the message was sent by the native android messages app, confusing Yoda with a new number.

If we could initiate text messages by the assistant through voip.ms, that would be aweome.
