### ISSUE TITLE
SMS won't stay marked as read

### ISSUE THREAD

**Issue by nihir** [michaelkourlas/voipms-sms-client#50]
Most of my sms messages are marked as read normally, but a few persistent and messages are always marked as unread, despite multiple efforts to manually mark them as read.

I've tried individually opening each message, selecting them and clicking mark as read, and reading them on the voip.ms website. I've even tried deleting data and cache, and starting the app as a fresh install. Nothing fixed it.  Every pull-to-refresh, my notifications are filled with "unread" SMS.  And they are the same ones every time.

**Comment by michaelkourlas** [comment]
Unfortunately, it's very difficult to figure out what might be causing the problem here, given the lack of information. Can you tell me anything else that might help? Any distinguishing features of the persistently marked unread messages, perhaps?

**Comment by nihir** [comment]
I completely understand.  I have solved the problem somewhat, by retrieving messages for a shorter time period.  It's quite possible that the messages were not marked as read on the Voip.ms server and the problem lay on their end.  Regardless, I haven't had the same issue in about a month.  If it reappears, I'll document the problem more thoroughly and report back.
