### ISSUE TITLE
Deleting a conversation not returning you back to main conversation list

### ISSUE THREAD

**Issue by alanchau** [michaelkourlas/voipms-sms-client#51]
Deleting a conversation while opened keeps you inside the conversation with the message "There are no messages in this conversation." instead of returning you back to the list of conversations.

**Comment by michaelkourlas** [comment]
Yeah, this isn't really ideal behaviour. Will fix in the 0.4.2 release.

**Comment by michaelkourlas** [comment]
This is now fixed.
