### ISSUE TITLE
Question: IP Whitelist for voip.ms API?

### ISSUE THREAD

**Issue by j--w** [michaelkourlas/voipms-sms-client#53]
When enabling the IP I need to put an IP address in for the IP invoker and it doesn't seem to let me put any wildcard patterns in, does this mean I'll only be able send and recieve mesages when on the whitelisted networks or do you have a workaround for that  that I may be missing?

**Comment by dkisselev** [comment]
I don't remember where i found this out (probably buried somewhere in their wiki, that thing has anything you would ever want to know, but is just very poorly organized), but 0 is the wildcard.

`0.0.0.0` allows everything.

**Comment by j--w** [comment]
Now that you mention it, that makes complete sense. Thank you very much.

**Comment by michaelkourlas** [comment]
This information is also available in the application's help section: https://github.com/michaelkourlas/voipms-sms-client/blob/master/voipms-sms/src/main/assets/help.html
