### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by krt16s** [michaelkourlas/voipms-sms-client#54]
This app includes Google's proprietary play-services depedency, what is it used for? Could you provide a pure-floss gradle flavor that does not require this (e.g. by stripping functionality or using floss alternatives)?

**Comment by anarcat** [comment]
@krt16s it is used (optionally, not on by default) for GCM notifications, see #37.

is this a blocker for froid inclusion (#36)?

**Comment by krt16s** [comment]
Gradle checks dependency before building, so it will try to find play-services and fail, because we dont have it on the buildserver. I can try to sort things out on our end, but having two separate build flavours is most likely the cleanest way to do it.

**Comment by michaelkourlas** [comment]
I'll be creating two different builds of the application this summer as part of the v0.4.2 release.

**Comment by baldurmen** [comment]
This is really appreciated! Many thanks!

**Comment by anarcat** [comment]
any word on that 0.4.2 release? can't wait!

**Comment by michaelkourlas** [comment]
I've created a special fdroid branch and removed the GCM and billing deps from that branch.

**Comment by krt16s** [comment]
Thanks, should build tonight: https://gitlab.com/fdroid/fdroiddata/commit/cba5e67c

**Comment by michaelkourlas** [comment]
@krt16s: You might want to remove push notifications from the app description, since the F-Droid version doesn't actually have those (no GCM).

**Comment by krt16s** [comment]
You are right, should be fixed tomorrow.

**Comment by michaelkourlas** [comment]
@krt16s: You'll also probably want to remove that last "and".
