### ISSUE TITLE
Support for other providers?

### ISSUE THREAD

**Issue by maneamarius** [michaelkourlas/voipms-sms-client#56]
Hi,

Will there be support for other SIP providers in the future?
Specifically, Flowroute. They have a Text messaging API available now:
https://www.flowroute.com/text-messaging-api/

I know your app is currently called Voip.ms SMS... but if we could add other SIP providers, maybe we can call it something more generic.. like SIP SMS or something similar.

I'd love to contribute to your app as well, as time permits. I have multiple DID's with Flowroute, we could use those for testing purposes.
I'm not an Android developer but have some experience with C# and scripting (bash, powershell), so I may be able to pickup quickly.

regards,
Marius

**Comment by michaelkourlas** [comment]
Unfortunately, I simply don't have the time to maintain an interface for two different APIs. Feel free to fork this app to create a "Flowroute SMS" app if you'd like, though!
