### ISSUE TITLE
Backup Voip.ms SMS to Gmail (similar to SMS backup+)

### ISSUE THREAD

**Issue by nihir** [michaelkourlas/voipms-sms-client#58]
I wanted to suggest a feature I love for backing up my actual normal/carrier sms and was wondering if you would consider implementing it.

I use an app called [SMS Backup+](https://github.com/jberkel/sms-backup-plus) which takes all SMS messages and backs them up regularly to Gmail in a folder.  This way my SMS is backed up and searchable anytime.

Here's the github for the app:
https://github.com/jberkel/sms-backup-plus/

It might be super difficult, or somewhat doable depending on whether you could leverage the code from that app, but it would really be an amazing addition to have a solid searchable backup that lives inside Gmail.

**Comment by Grogdor** [comment]
Login to VoIP.ms and under the "DID Numbers" heading, go to "Manage DIDs". Edit your DID that has SMS option. Near the bottom there's an option to set an "SMS Email Address" that will accomplish the same thing that you're after.

**Comment by nihir** [comment]
I understand that option exists for received messages, but by using the
app, it wouldn't capture sent messages.

It may be a niche option, but thanks for replying anyway.

**Comment by michaelkourlas** [comment]
Unfortunately, I don't think adding support for apps like SMS Backup+ is really possible since those apps read SMS messages from the main Android SMS database, which VoIP.ms SMS doesn't use.

However, you can make regular (manual) copies of the entire database if you go to Settings and click "Edit message database".
