### ISSUE TITLE
Limit reached (303)

### ISSUE THREAD

**Issue by cramcramm** [michaelkourlas/voipms-sms-client#67]
I keep getting this error when I try to send messages. Do I have a text limit I am allowed to send each day? This happened before too and the next day it worked fine until now. The web portal still let's me send messages from there.

**Comment by TerrenceHung** [comment]
According to the voip.ms API docs (https://voip.ms/m/apidocs.php), there is an error code called limit_reached which can be triggered by reaching the maximum amount of SMS messages per day, so I don't think there's anything we can do about it.

I can't find what the actual limit per day is though.

**Comment by cramcramm** [comment]
Yea I thought it was an issue with the VoIP.ms service until I went on their actual website sms portal and was still able to send messages no problem. It only limited it me on the app.


- Jonas Cramm


-------- Original message --------

**Comment by hackmyl1fe** [comment]
I had the same issue, and IIRC the limit is something like 100/day. I opened a ticket with them and asked if they could increase the limit since i was clearly not using voip.ms to send spam SMS. It took like a week or two before they were able to increased it but they did. I think its at 200/day now

**Comment by cramcramm** [comment]
Wow that's it, only 200 messages a day. Why is there such a low limit? I guess VoIP.ms needs to come out with their own sms app haha. I have kind of moved away from texting anyways since singing up with VoIP.ms but it is still a pain in the butt to have a daily limit. There is no way around it? Thanks for the info.


- Jonas Cramm


-------- Original message --------

**Comment by hackmyl1fe** [comment]
Ya the only way around it is to open a ticket. You can maybe ask to increase it to 300 or 400 and see what they say

**Comment by cramcramm** [comment]
Oh so it's a by user request kind of thing? I juat open a trouble ticket through the app?


- Jonas Cramm


-------- Original message --------

**Comment by michaelkourlas** [comment]
This is a VoIP.ms issue, unfortunately -- as other users have said, you'll have to ask them to increase the API SMS rate limit.
