### ISSUE TITLE
Configurable conversation input box

### ISSUE THREAD

**Issue by guiweber** [michaelkourlas/voipms-sms-client#70]
The input box is large enough to display around 90 characters (4 lines of text). When typing longer messages, a part of the message will be hidden. While it is possible to scroll up and down to see the hidden parts of the message it would be nice to be able to see more at once, especially on larger devices where space is not an issue.

**Comment by michaelkourlas** [comment]
I chose the current behaviour such that it was the same as Google Messenger's behaviour -- auto-expand up to 4 lines. Any more than that would look awkward on small devices, I think.

I suppose I could add an option in the settings.

**Comment by guiweber** [comment]
I don't have much experience developing for Android, but can't the box size or the layout be different for different screen sizes?

**Comment by michaelkourlas** [comment]
Probably? I'm not sure what size would make the most sense for a given screen size, though.

**Comment by julianlam** [comment]
Hey @michaelkourlas, we noticed the input box got bigger in the newest release of the app (w/ Kotlin rewrite). Perhaps this can be closed?

**Comment by michaelkourlas** [comment]
No, because this bug is about changing the size of the input box depending on the screen size.

**Comment by michaelkourlas** [comment]
This has been implemented.
