### ISSUE TITLE
SMS notifications don't always get through

### ISSUE THREAD

**Issue by mhdawson** [michaelkourlas/voipms-sms-client#71]
I'm enjoying the application but am wondering if there is some additional configuration I need on my phone.  

I have gotten the notifications to work a couple times by enabling or re-enabling notifications but then either after the phone has been off for a while or something else I don't get the notification when a new text arrives. 

Right now it does not seem to notify me even after enable/disable.

**Comment by hackmyl1fe** [comment]
I've had the app for over 4 months now and last week the notifications stopped working. I've wiped cache, app data, re-installed it and nothing worked. I though it was my phone but I'm happy to see I'm not the only one

**Comment by mhdawson** [comment]
Just tried again with an sms from another number and worked that time (was sending from same number to itself before  to test).  Will let phone sit for a while and see if I still get the notification sending from that number later on.

**Comment by mhdawson** [comment]
Still worked 10 minutes later, will try leaving it for longer time.

**Comment by zachRudz** [comment]
I've also experienced this problem. Recently had a few texts that push
notifications didn't come in until the following day, problem showed up
about a week ago.

It's possible that this issue could be related to the SMS callback server.
I'm using the developer's server, here:
https://github.com/michaelkourlas/voipms-sms-server. Are you guys also
using this server?

**Comment by mhdawson** [comment]
I'm just using whatever the app uses by default, I don't see anywhere in the GUI to configure it.

**Comment by hackmyl1fe** [comment]
Ya just using the default

**Comment by zachRudz** [comment]
In voip.ms, check out DID Numbers -> Manage DID. Click the orange square to
edit one of your DIDs, and scroll to the bottom for SMS-related options.
One of the fields is labeled "SMS URL Callback". If that has "
http://voipmssms-kourlas.rhcloud.com/sms_callback?did={TO}" in the field,
then you're using the developer's server.

It was a while ago that I set this up, I can't remember if this is the
app's default callback URL.

**Comment by mhdawson** [comment]
Yes found it, I'm using the same one.

**Comment by mhdawson** [comment]
Still worked 26 minutes later.

**Comment by michaelkourlas** [comment]
A few days ago I pushed an update to the callback server that briefly broke notifications. It should be fixed now. Let me know if you still have an issue.

**Comment by mhdawson** [comment]
And still ok 41 mins later.  I was having issues earlier but maybe it was related to the to/from being the same.  In any case if I have problems again I'll try to narrow down when/what causes it.

**Comment by michaelkourlas** [comment]
For the record, until VoIP.ms adds native reliable GCM support, notifications are always going to be a little hit and miss. 

Under the current system, when you receive an SMS, VoIP.ms sends a message to a server I maintain with your DID. The server maintains a database matching DIDs with Google Cloud Messaging registration numbers. When it receives a message from VoIP.ms, it sends a message to Google telling them to push a notification to your phone. There are many things that can go wrong here. :P

**Comment by ASalvail** [comment]
Is there a way to have some kind of keep alive however on the app? Since Marshmallow, the phone is much more aggressive in trying to put apps to sleep.

**Comment by michaelkourlas** [comment]
You're right, and I believe Google's solution to that is... you guessed it, GCM.

**Comment by Snuupy** [comment]
push notifications don't work properly for me.

The only way for me to get push notifications working was:
1. keep VoIP.ms SMS app open
2. after looking through the source, I set the callback URL to `http://voipmssms-kourlas.rhcloud.com/sms_callback?did=MY10DIGITPHONENUMBERHERE` (replace MY10DIGITPHONENUMBERHERE with your DID)
3. send a test text to your DID, you should receive a push notification.
setting the callback URL to `http://voipmssms-kourlas.rhcloud.com/sms_callback?did={TO}` doesn't work for me.

pressing back on the app or switching to something else will mess up the push notifications. can anyone else confirm?
