### ISSUE TITLE
Add character counter to input box

### ISSUE THREAD

**Issue by guiweber** [michaelkourlas/voipms-sms-client#72]
Since collated SMS are not supported at this point as per #69, it would be nice to have some sort of character counter in the input box. This would allow users to know when their message reaches the character limit. The current implementation automatically splits messages at the 160 character limit without warning the user, which more often than now causes words to be cut in two.

The character counter should include the number of character in the message, and the maximum length for a single message:
xx/160

**Comment by michaelkourlas** [comment]
Google Messenger adds a small counter to the bottom right of the text box when you have 10 or so characters left. I think I'll do the same.

**Comment by michaelkourlas** [comment]
This is now implemented.
