### ISSUE TITLE
Manage LED

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#75]
Thanks for the 0.4.2 version!

One thing I would like to see would be LED support. It's nice not to have to unlock your device to see you have a new sms.

Being able to choose the LED color would be nice add on to this.

**Comment by michaelkourlas** [comment]
LED support already exists -- you just can't change the colour.

**Comment by bellmork** [comment]
I would like to use Light Flow PRO for this instead.  Is there a chance it could be easier for such third party apps to catch a from did, cnam, or body text?

**Comment by michaelkourlas** [comment]
Will add support for this once Android O is released.

**Comment by michaelkourlas** [comment]
This has been implemented and will be in 0.6.0.
