### ISSUE TITLE
Migrate from GCM to FCM

### ISSUE THREAD

**Issue by michaelkourlas** [michaelkourlas/voipms-sms-client#77]

**Comment by anarcat** [comment]
for those who don't know what FCM is, it's google's upgrade to GCM based on Firebase a realtime database aquired by Google recently:

http://stackoverflow.com/questions/37452463/fcm-vs-gcm-why-we-need-to-migrate-from-gcm-to-fcm
https://developers.google.com/cloud-messaging/faq
https://en.wikipedia.org/wiki/Firebase

an interesting thing with FCM is that there are a number of free software alterantives to Firebase that make it possible / easier to implement a non-google endpoint for those notifications:

http://alternativeto.net/software/firebase/
https://www.npmjs.com/package/firebase-server
https://www.quora.com/Whats-the-closest-open-source-alternative-to-Firebase

**Comment by michaelkourlas** [comment]
This is now implemented.
