### ISSUE TITLE
Not seeing any messages since the 0.4.2 update

### ISSUE THREAD

**Issue by guiweber** [michaelkourlas/voipms-sms-client#78]
Since the 4.2 update, my conversation list says "You have no messages". However if I select a contact from the contact list I can see my message history with this person indicating that the messages are still present on the device. I am receiving new message notifications as well, but the conversation list stays empty even after receiving new messages. Performing  a full sync with the server doesn't fix the issue.

**Comment by michaelkourlas** [comment]
That's bizarre. I did some basic upgrade testing before I released the new version and I was able to view my old messages just fine.

Would you be willing to email me a copy of your database -- maybe with all the message text removed or something -- so that I can figure out what's going on?

**Comment by michaelkourlas** [comment]
Also, it looks like you're not the only person with this issue :(

**Comment by guiweber** [comment]
sure, is there an easy way to export the database?

**Comment by michaelkourlas** [comment]
Yes, go to Settings, click "Edit message database", and copy the contents of the textbox. It's a JSON dump of the database.

**Comment by guiweber** [comment]
Will you be able to troubleshoot it if I remove the DID and contact entries (I will replace the values with "")?

**Comment by guiweber** [comment]
[database.txt](https://github.com/michaelkourlas/voipms-sms-client/files/477826/database.txt)

**Comment by demonicpancake** [comment]
Same here!

**Comment by stoobz** [comment]
Experiencing this issue as well.

**Comment by Playdifferent** [comment]
Yeah I am also experiencing this issue!

**Comment by michaelkourlas** [comment]
I've tried to duplicate this bug with a database dump someone sent me and I can't. My test device is a OnePlus One running Android 6.0.1. What versions of Android are other people running?

**Comment by stoobz** [comment]
I'm using an s5 active, unfortunately still stuck on 4.4.2. Is there a way I can download the older version?

Thanks for the app and continued support :)

**Comment by michaelkourlas** [comment]
Yes, anyone can download the older version using the Releases section on GitHub.

**Comment by michaelkourlas** [comment]
Has anybody tried reinstalling the app and trying to download messages from VoIP.ms? If you still can't see messages in the conversation view, that would mean the issue probably has to do with the DB function that gets conversations, which was changed in 0.4.2.

**Comment by stoobz** [comment]
Just uninstalled and reinstalled it. Set the date back and still no messages. I download the 0.4.1 and seems to work for me. Thanks for your help

**Comment by Playdifferent** [comment]
I still have kit Kat and can't update..  I hear this is a problem with Android and carriers?

**Comment by grichaud** [comment]
I have the same issue. =( 
Also the settings are acting up. When I set Retrieve Only Recet on, Retrieve Deleted Messages sets on as well. When I scroll down the settings screen and scroll up again, Retrieve Only Recent sets off. It's very strange.

**Comment by guiweber** [comment]
I'm also on Android 4.4.2

**Comment by demonicpancake** [comment]
same here: android 4.4.2

**Comment by stoobz** [comment]
I went back to the 0.4.1 version, which was working for me... this morning it updated to the new version (no messages again). Is there a way to stop just this app from updating until there's a fix?

**Comment by michaelkourlas** [comment]
There's a setting in Google Play to turn off automatic updates.

**Comment by michaelkourlas** [comment]
Finally got the emulator working and discovered the problem:

```
09-19 00:53:13.369 5673-5715/net.kourlas.voipms_sms E/SQLiteLog: (1) no such collation sequence: UTF8_GENERAL_CI
09-19 00:53:13.369 5673-5715/net.kourlas.voipms_sms W/Filter: An exception occured during performFiltering()!
                                                              android.database.sqlite.SQLiteException: no such collation sequence: UTF8_GENERAL_CI (code 1): , while compiling: SELECT * FROM sms a INNER JOIN (SELECT DatabaseId, Contact, MAX(Date) AS Date FROM sms WHERE (Text LIKE ? COLLATE UTF8_GENERAL_CI) AND Did=5143121304 AND Deleted=0 GROUP BY Contact) b on a.DatabaseId = b.DatabaseId AND a.Date = b.Date ORDER BY Date DESC, DatabaseId DESC
```

Apparently older Android versions use a version of SQLite that doesn't support certain collation sequences.

**Comment by michaelkourlas** [comment]
I've found an easy fix that should be released shortly.

**Comment by guiweber** [comment]
Thanks for the quick fix : )

**Comment by stoobz** [comment]
Thanks for the fix!
