### ISSUE TITLE
Sync on/off settings act strange

### ISSUE THREAD

**Issue by electoys** [michaelkourlas/voipms-sms-client#81]
When I try to change the value of one of the 4 Settings->Synchronization Retrieve or Propagate on/off settings, the others change.  The behaviour is spuradic.   For example trying to enable the first one, "Retrieve only recent messages..." the 2nd and 3rd one switch on and not the one I selected.  If I then turn off the 2nd one...nothing changes.   Turning off the 3rd one, the 2nd and 3rd turn off and the 1st one turns on!  Also sometimes if I exit settings and reenter it, these 4 settings are different!

VoIP.ms SMS app version 0.4.2.
Android 4.4.4.

**Comment by michaelkourlas** [comment]
I can't reproduce on Android 6.0. I'll keep investigating.

**Comment by electoys** [comment]
Michael,  I'll try on a 6.0 device too.  But for many of us running 4.4, judging by the comments on and subscribers to issue #78, do you have a KitKat device?

**Comment by michaelkourlas** [comment]
No, and for some reason I'm having great difficulty getting my IDE to talk
to the Android emulator.

**Comment by michaelkourlas** [comment]
Reproduced on the emulator, but it turns out this is an Android bug: https://code.google.com/p/android/issues/detail?id=26194

**Comment by michaelkourlas** [comment]
Found a fix that should be released shortly.

**Comment by electoys** [comment]
Nice sleuthing.  I'll give the app a test drive and then donate!
