### ISSUE TITLE
Not receiving most push notifications from voip.ms sms since upgrading to Android 7

### ISSUE THREAD

**Issue by janvitos** [michaelkourlas/voipms-sms-client#85]
Hi,

First of all, thank you so much for this great app. It's really one of a kind and so useful since I've been using voip.ms as my main mobile phone service.

So I've recently upgraded my Nexus 5X phone to Android 7, and I've noticed that I don't receive most notifications anymore from voip.ms sms. It seems like I only get notifications when my phone is being used or has been idle only for a few minutes. After a while, I stop receiving all messages & notifications and I have to go into the app to see the messages finally come in.

I've tried uninstalling, clearing data & reinstalling the app to see if it would help, but the problem persisted.

I just recently turned off battery optimizations for voip.ms sms to see what impact (if any) it will have on it.

I happen to have a Nexus 5 phone with Android 6, and it has no problem receiving messages & push notifications from voip.sms sms.

Has anyone else experienced this issue since upgrading to Android 7?

Thank you.

Janvitos

**Comment by michaelkourlas** [comment]
I don't own an Android 7 device, and unfortunately [this bug](https://code.google.com/p/android/issues/detail?id=223100) has made it impossible to test the app on an Android 7 emulator for the time being. Hopefully once it's fixed I'll be able to investigate.

**Comment by janvitos** [comment]
Just to let you know, after disabling battery optimizations, letting the phone sit idle for a few hours and sending myself some messages, the messages were received instantaneously with the push notifications.

So I believe this might have something to do with Android 7's new battery optimization technique.

As read on https://www.thurrott.com/mobile/android/77553/android-7-0-nougat-tip-manage-battery-life

Note: Android lets you opt your favorite apps out of Doze so that they can notify you even when the system is sleeping. To do so—at the expense of battery life, of course—navigate to Battery settings and choose Menu (“…”) and then Battery optimization. Then, display the All Apps view, tap the correct app, and choose “Don’t optimize.”

This is exactly what I did and it seems to have fixed the issue for the time being.

Not sure about battery drain though, but I doubt your app will consume much battery if sync options are all turned off.

**Comment by michaelkourlas** [comment]
Technically, the GCM messages sent don't contain any information about the SMS received for privacy reasons. This means that the app has to perform a partial sync every time a GCM message is received; Doze might not be letting the app do that. 

I can try adding the "high priority" marker to FCM messages sent to the device.

**Comment by janvitos** [comment]
That was my initial reasoning behind this: Doze is probably preventing the messages from entering.

If you can add high priority to the FCM messages, then I would gladly test the app for you if there's a way for me to do so.

**Comment by michaelkourlas** [comment]
It's done -- feel free to give it a shot.

**Comment by janvitos** [comment]
Can you provide a link to an APK, or should I compile it myself from the repo ?

**Comment by janvitos** [comment]
Oh I see this was done at the server level, so I guess I can test without updating the app.

Will do so and get back to you on this asap.

Thanks.

**Comment by janvitos** [comment]
So I've already made some tests, and it seems to be looking good!

I've re-enabled battery optimizations for the app and received every message & push notification for the tests I made.

Though, this is limited to a few texts I sent to myself from another device. Tomorrow, I should be able to confirm if everything is fixed with texts received from different people at different times.

**Comment by janvitos** [comment]
Well after some more testing today, I can confirm I received all text messages from different senders while the phone was in Doze mode at all times.

**Comment by michaelkourlas** [comment]
Excellent!
