### ISSUE TITLE
Add contact by the app

### ISSUE THREAD

**Issue by nathanbegin** [michaelkourlas/voipms-sms-client#92]

**Comment by michaelkourlas** [comment]
Sorry, could you clarify what you mean by "add contact by the app"?

**Comment by nathanbegin** [comment]
For example: 

111-222-3344 sent me a SMS and I want that number to be add to my contacts.

**Comment by michaelkourlas** [comment]
This feature already exists. If you click on the profile picture associated with the phone number, you'll be prompted to create a contact with that phone number.
