### ISSUE TITLE
When synchronisation is enabled, it doesn't treat push notifications

### ISSUE THREAD

**Issue by hubearth** [michaelkourlas/voipms-sms-client#93]
The title says it all. I'm not sure if it's a bug or it's wanted that way.

**Comment by michaelkourlas** [comment]
Sorry, I'm not sure what you mean. Are you saying that if synchronization is enabled, push notifications no longer work?

**Comment by hubearth** [comment]
Yes, that's what I mean. It will wait to syncronise instead of responding to  the push notification

Le 11 octobre 2016 02:21:03 HAE, Michael Kourlas <notifications@github.com> a écrit :
>Sorry, I'm not sure what you mean. Are you saying that if
>synchronization is enabled, push notifications no longer work?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/michaelkourlas/voipms-sms-client/issues/93#issuecomment-252823977

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by michaelkourlas** [comment]
I'm afraid I can't reproduce this. On my device, push notifications are still received with synchronization enabled. Try turning push notifications off and on again if you're having problems.
