### ISSUE TITLE
Fuse long SMS into a single message

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#94]
When I receive long SMS the messages appear as multiple messages, sometimes cutting a word in half. It's cosmetic, but it can be bothering.

I know this is the behavior of the VOIP.ms SMS web interface, but would it be possible to merge SMS messages received close one to another (~30s) into a single message?

If it is something that VOIP,ms should change directly, please say so so I can open an Feature Request.

**Comment by sadortun** [comment]
Also, long messages parts are often not displayed in the correct order.

**Comment by michaelkourlas** [comment]
I've decided not to implement support for this at the app level. The solution is for VoIP.ms to properly support [concatenated SMS](https://en.wikipedia.org/wiki/Concatenated_SMS).
