### ISSUE TITLE
Tasker integration or shell command to trigger syncronization

### ISSUE THREAD

**Issue by pcpumpkin** [michaelkourlas/voipms-sms-client#95]
Having inconsistencies with FCM triggering a synchronization.  Currently have voip.ms automatically forwarding sms to my data tablet plan ( I have FIDO free unlimited incoming sms ).  Forwarded sms are consistently coming through.  

I am working on a specific workaround that may work for me.  I realize this may not apply to others.  

Requesting either Tasker integration or shell command, javascript file I can put into Tasker so that it can trigger Voip.ms SMS to trigger the same routine synchronization that is initiated by FCM.   I am planning to use Tasker to trigger synchronization when receiving any sms sent from Voip.ms .  Hoping to avoid FCM altogether.       

Thanks

**Comment by michaelkourlas** [comment]
I don't think enough people will use this feature to justify the work involved in implementing it, especially if the underlying problems with FCM can be fixed.
