### ISSUE TITLE
No Notifications if Any Drafts Exist over extended period

### ISSUE THREAD

**Issue by jasonrfgm** [michaelkourlas/voipms-sms-client#96]
I noticed I wasnt getting any new text Notifications for nearly a week, then I noticed that my draft measages were always on top and superceding any new messages, even if just a " " space. Cleared drafts AND database before Notifications resumed

**Comment by michaelkourlas** [comment]
Probably a bug. I'll look into it.

**Comment by michaelkourlas** [comment]
I think this problem is fixed in 0.5.0, as the way the app internally tracks drafts is quite different now.
