### ISSUE TITLE
RCS Support

### ISSUE THREAD

**Issue by julianlam** [michaelkourlas/voipms-sms-client#99]
Hey there, is there any chance this app (and VoIP.ms itself) can support the RCS protocol?

http://mobilesyrup.com/2016/12/13/rcs-messaging-is-now-available-to-some-rogers-and-fido-customers/

No complaints about the app, keep up the good work!

**Comment by michaelkourlas** [comment]
It's up to VoIP.ms whether they want to support that and expose it through their API. Unfortunately that's probably not going to happen.
